"""
Geo-JEPA Simple: MLP Encoder + MCR² Loss + JEPA Training
==========================================================
Simplified version that validates room separation before adding complexity.

Architecture:
  Encoder:   MLP (gene_dim -> hidden -> embed_dim) with L2 normalization
  MCR² loss: coding rate formulation from u-CTRL (d×d eigvalsh, MPS-native)
  JEPA:      Gene-set masking + EMA target encoder + predictor MLP

This replaces the fragile ReduNet/Cholesky pipeline with a stable MLP encoder
that learns structure purely from the MCR² + JEPA objectives. Once rooms
separate (DR > 2.0), we can swap the MLP for attention + ReduNet.

Dataset: MNIST proxy (generated by build_proxy_dataset.py)
"""

# %% [1] Imports & Setup
import json
import time
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
import umap
from pathlib import Path
from torch.utils.data import Dataset, DataLoader
from copy import deepcopy

DEVICE = torch.device(
    "mps" if torch.backends.mps.is_available()
    else "cuda" if torch.cuda.is_available()
    else "cpu"
)
print(f"Using device: {DEVICE}")

# %% [2] Configuration
CONFIG = {
    "data_dir":         "./data",
    "embed_dim":        128,
    "hidden_dim":       512,
    "predictor_hidden": 256,
    "context_ratio":    0.75,
    "ema_momentum":     0.996,
    "mcr_weight":       1.0,       # MCR² weight — start high to force separation
    "eps":              0.5,
    "batch_size":       512,       # larger batches help MCR² see class structure
    "epochs":           40,
    "lr":               1e-3,
    "weight_decay":     1e-4,
    "diag_every":       10,
}

# %% [3] Dataset
def load_proxy_dataset(data_dir: str = "./data"):
    """Load pre-built proxy dataset from .npz file."""
    npz_path = Path(data_dir) / "proxy_dataset.npz"
    meta_path = Path(data_dir) / "proxy_dataset_metadata.json"

    if not npz_path.exists():
        raise FileNotFoundError(
            f"Dataset not found at {npz_path}. "
            "Run first: python build_proxy_dataset.py"
        )

    data = np.load(npz_path)
    with open(meta_path) as f:
        meta = json.load(f)

    pert_cells = data["perturbation_cells"]
    pert_ids = data["perturbation_ids"]
    pert_strengths = data["perturbation_strengths"]
    pert_names = meta["perturbation_names"]

    perturbed = []
    for pid in sorted(set(pert_ids)):
        for strength in sorted(set(pert_strengths[pert_ids == pid])):
            mask = (pert_ids == pid) & (pert_strengths == strength)
            cells = pert_cells[mask]
            name = f"{pert_names[str(pid)]}_s{strength}"
            labels = np.full(len(cells), pid, dtype=int)
            perturbed.append((cells, labels, name))

    homeostatic = data["homeostatic_cells"]
    gene_dim = homeostatic.shape[1]
    print(f"Dataset loaded: {homeostatic.shape[0]} homeostatic, "
          f"{gene_dim}D, ~{100*(homeostatic==0).mean():.0f}% zeros")

    return {
        "homeostatic": homeostatic,
        "class_labels": data["homeostatic_labels"],
        "perturbed": perturbed,
        "ood_test": (data["ood_cells"], data["ood_labels"], "ood_toward_7"),
        "room_digits": meta["room_digits"],
    }


class CellDataset(Dataset):
    def __init__(self, cells: np.ndarray, labels: np.ndarray):
        self.cells = torch.from_numpy(cells).float()
        self.labels = torch.from_numpy(labels).long()

    def __len__(self):
        return len(self.cells)

    def __getitem__(self, idx):
        return self.cells[idx], self.labels[idx]


data = load_proxy_dataset(CONFIG["data_dir"])
n_classes = len(data["room_digits"])
gene_dim = data["homeostatic"].shape[1]

dataset = CellDataset(data["homeostatic"], data["class_labels"])
loader = DataLoader(dataset, batch_size=CONFIG["batch_size"],
                    shuffle=True, num_workers=0, pin_memory=False)

# %% [4] MCR² Loss (d×d formulation — stable on MPS, no Cholesky)
def coding_rate(Z: torch.Tensor, eps: float = 0.5) -> torch.Tensor:
    """
    R(Z, eps) = (d/2) log det(I + d/(n*eps^2) Z^T Z)
    Uses eigvalsh on (d×d) matrix — works on MPS without fallback.
    """
    n, d = Z.shape
    alpha = d / (n * eps ** 2)
    M = torch.eye(d, device=Z.device) + alpha * (Z.T @ Z)
    if M.device.type == "mps":
        eigvals = torch.linalg.eigvalsh(M.cpu()).to(Z.device)
    else:
        eigvals = torch.linalg.eigvalsh(M)
    return 0.5 * torch.sum(torch.log(eigvals.clamp(min=1e-7)))


def mcr2_loss(Z, labels, n_classes, eps=0.5):
    """MCR² with hard labels. Returns (loss, R_total, R_compress, delta_R)."""
    R_total = coding_rate(Z, eps)
    R_compress = torch.tensor(0.0, device=Z.device)
    n = Z.shape[0]
    for k in range(n_classes):
        mask = labels == k
        n_k = mask.sum()
        if n_k < 2:
            continue
        R_compress = R_compress + (n_k / n) * coding_rate(Z[mask], eps)

    delta_R = R_total - R_compress
    return -delta_R, R_total.item(), R_compress.item(), delta_R.item()

# %% [5] Models
class MLPEncoder(nn.Module):
    """MLP encoder: gene_dim -> hidden -> embed_dim, L2 normalized.
    Placeholder for future attention + ReduNet."""
    def __init__(self, gene_dim, embed_dim, hidden_dim=512):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(gene_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, embed_dim),
        )

    def forward(self, x):
        return F.normalize(self.net(x), dim=1)


class Predictor(nn.Module):
    """MLP predictor: z_context -> z_target_hat."""
    def __init__(self, embed_dim, hidden_dim=256):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(embed_dim, hidden_dim),
            nn.GELU(),
            nn.LayerNorm(hidden_dim),
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, embed_dim),
        )

    def forward(self, z):
        return F.normalize(self.net(z), dim=1)


def gene_set_mask(x, context_ratio=0.75):
    """Partition genes into context (visible) and target (masked)."""
    gene_dim = x.shape[1]
    n_context = int(gene_dim * context_ratio)
    perm = torch.randperm(gene_dim, device=x.device)
    x_context = torch.zeros_like(x)
    x_context[:, perm[:n_context]] = x[:, perm[:n_context]]
    x_target = torch.zeros_like(x)
    x_target[:, perm[n_context:]] = x[:, perm[n_context:]]
    return x_context, x_target


@torch.no_grad()
def ema_update(online, target, momentum=0.996):
    for p_o, p_t in zip(online.parameters(), target.parameters()):
        p_t.data.mul_(momentum).add_(p_o.data, alpha=1.0 - momentum)


# Build models
encoder_online = MLPEncoder(gene_dim, CONFIG["embed_dim"], CONFIG["hidden_dim"]).to(DEVICE)
encoder_target = deepcopy(encoder_online).to(DEVICE)
for p in encoder_target.parameters():
    p.requires_grad_(False)
predictor = Predictor(CONFIG["embed_dim"], CONFIG["predictor_hidden"]).to(DEVICE)

params = list(encoder_online.parameters()) + list(predictor.parameters())
n_params = sum(p.numel() for p in params if p.requires_grad)
print(f"Model: {n_params:,} params, embed_dim={CONFIG['embed_dim']}")

params = list(encoder_online.parameters()) + list(predictor.parameters())
optimizer = torch.optim.AdamW(params, lr=CONFIG["lr"],
                              weight_decay=CONFIG["weight_decay"])
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer, T_max=CONFIG["epochs"]
)

# %% [6] Diagnostics
@torch.no_grad()
def compute_diagnostics(encoder, data, epoch):
    """Compute and display diagnostic plots: UMAP + orthogonality heatmap."""
    encoder.eval()

    # Embed all homeostatic cells
    cells = torch.from_numpy(data["homeostatic"]).float().to(DEVICE)
    labels = data["class_labels"]
    room_digits = data["room_digits"]
    all_z = []
    for i in range(0, len(cells), 256):
        all_z.append(encoder(cells[i:i+256]).cpu())
    Z = torch.cat(all_z, dim=0).numpy()
    n_cls = len(room_digits)

    # Orthogonality matrix (cosine similarity between room centroids)
    centroids = np.zeros((n_cls, Z.shape[1]))
    for k in range(n_cls):
        mask = labels == k
        if mask.sum() > 0:
            centroids[k] = Z[mask].mean(axis=0)
    norms = np.linalg.norm(centroids, axis=1, keepdims=True) + 1e-8
    centroids_norm = centroids / norms
    ortho = centroids_norm @ centroids_norm.T

    # Per-class coding rates
    Z_tensor = torch.from_numpy(Z).float()
    R_total = coding_rate(Z_tensor, eps=0.5).item()
    class_rates = []
    for k in range(n_cls):
        mask = labels == k
        if mask.sum() >= 2:
            class_rates.append((room_digits[k], coding_rate(Z_tensor[mask], eps=0.5).item(), int(mask.sum())))
        else:
            class_rates.append((room_digits[k], 0.0, int(mask.sum())))

    # Print summary
    print(f"\n  [Diagnostics @ epoch {epoch}]")
    print(f"  R(Z) total = {R_total:.2f}")
    for digit, rate, count in class_rates:
        print(f"    R(Z_{digit}) = {rate:.2f}  (n={count})")
    R_compress = sum(r * n / len(Z) for _, r, n in class_rates)
    print(f"  R_compress = {R_compress:.2f},  delta_R = {R_total - R_compress:.2f}")
    off_diag = ortho[~np.eye(n_cls, dtype=bool)].mean()
    print(f"  Ortho: diag_mean={np.diag(ortho).mean():.3f}, off_diag_mean={off_diag:.3f}")

    # UMAP + heatmap
    reducer = umap.UMAP(metric="cosine", n_neighbors=15)
    emb_2d = reducer.fit_transform(Z)

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    axes[0].scatter(emb_2d[:, 0], emb_2d[:, 1], c=labels, cmap="tab10", s=8, alpha=0.5)
    for k in range(n_cls):
        mask = labels == k
        if mask.sum() > 0:
            cx, cy = emb_2d[mask].mean(axis=0)
            axes[0].annotate(str(room_digits[k]), (cx, cy),
                            fontsize=14, fontweight="bold", ha="center",
                            color="black",
                            bbox=dict(boxstyle="round,pad=0.2", fc="white", alpha=0.8))
    axes[0].set_title(f"UMAP of Z (epoch {epoch})")
    axes[0].set_xticks([])
    axes[0].set_yticks([])

    im = axes[1].imshow(ortho, cmap="RdBu_r", vmin=-1, vmax=1)
    axes[1].set_xticks(range(n_cls))
    axes[1].set_xticklabels(room_digits)
    axes[1].set_yticks(range(n_cls))
    axes[1].set_yticklabels(room_digits)
    axes[1].set_title(f"Room Cosine Similarity (epoch {epoch})")
    fig.colorbar(im, ax=axes[1], shrink=0.8)

    plt.tight_layout()
    plt.show()

    encoder.train()
    return ortho, R_total


@torch.no_grad()
def evaluate_discrimination(encoder, data):
    """Compute discrimination ratio for fate-A perturbation."""
    encoder.eval()

    room_embeddings = {}
    for label_idx, digit in enumerate(data["room_digits"]):
        mask = data["class_labels"] == label_idx
        cells = torch.from_numpy(data["homeostatic"][mask]).float().to(DEVICE)
        if len(cells) == 0:
            continue
        embs = []
        for i in range(0, len(cells), 256):
            embs.append(encoder(cells[i:i+256]))
        room_embeddings[digit] = torch.cat(embs, dim=0).mean(dim=0)

    fate_A_cells = None
    for cells, labels, name in data["perturbed"]:
        if "fate_A" in name and "s1.0" in name:
            fate_A_cells = torch.from_numpy(cells).float().to(DEVICE)
            break

    if fate_A_cells is None or 4 not in room_embeddings or 1 not in room_embeddings:
        print("  Could not evaluate: missing data")
        encoder.train()
        return 0.0

    embs = []
    for i in range(0, min(len(fate_A_cells), 256), 128):
        embs.append(encoder(fate_A_cells[i:i+128]))
    z_pert = torch.cat(embs, dim=0).mean(dim=0)

    dist_correct = (z_pert - room_embeddings[4]).norm().item()
    dist_wrong = (z_pert - room_embeddings[1]).norm().item()
    ratio = dist_wrong / (dist_correct + 1e-8)

    print(f"  DR = {ratio:.2f}x  (d_correct={dist_correct:.4f}, d_wrong={dist_wrong:.4f})")
    if ratio > 2.0:
        print("  PASSED: Linearization Trap avoided")
    elif ratio > 1.0:
        print("  PARTIAL: Correct direction, not strongly discriminated")
    else:
        print("  FAILED: Cannot discriminate fate outcomes")

    encoder.train()
    return ratio

# %% [7] Training Loop
all_params = list(encoder_online.parameters()) + list(predictor.parameters())

print(f"\nTraining for {CONFIG['epochs']} epochs "
      f"(mcr_weight={CONFIG['mcr_weight']}, context_ratio={CONFIG['context_ratio']})\n")

total_time = 0.0
for epoch in range(1, CONFIG["epochs"] + 1):
    encoder_online.train()
    predictor.train()

    ep_pred, ep_mcr, ep_dr = 0.0, 0.0, 0.0
    n_batches = 0
    t0 = time.perf_counter()

    for x_batch, y_batch in loader:
        x_batch = x_batch.to(DEVICE)
        y_batch = y_batch.to(DEVICE)

        x_ctx, x_tgt = gene_set_mask(x_batch, CONFIG["context_ratio"])

        z_ctx = encoder_online(x_ctx)
        with torch.no_grad():
            z_tgt = encoder_target(x_tgt)

        z_pred = predictor(z_ctx)

        pred_loss = F.mse_loss(z_pred, z_tgt.detach())
        mcr_loss, R_tot, R_comp, dR = mcr2_loss(
            z_ctx, y_batch, n_classes, eps=CONFIG["eps"]
        )
        loss = pred_loss + CONFIG["mcr_weight"] * mcr_loss

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(all_params, max_norm=1.0)
        optimizer.step()
        ema_update(encoder_online, encoder_target, CONFIG["ema_momentum"])

        ep_pred += pred_loss.item()
        ep_mcr += mcr_loss.item()
        ep_dr += dR
        n_batches += 1

    elapsed = time.perf_counter() - t0
    total_time += elapsed
    scheduler.step()
    avg_pred = ep_pred / n_batches
    avg_mcr = ep_mcr / n_batches
    avg_dr = ep_dr / n_batches
    lr_now = scheduler.get_last_lr()[0]

    print(f"Epoch {epoch:3d}/{CONFIG['epochs']} | "
          f"pred={avg_pred:.4f} | mcr={avg_mcr:.2f} | "
          f"dR={avg_dr:.2f} | lr={lr_now:.2e} | {elapsed:.1f}s")

    if epoch % CONFIG["diag_every"] == 0 or epoch == 1 or epoch == CONFIG["epochs"]:
        compute_diagnostics(encoder_online, data, epoch)
        evaluate_discrimination(encoder_online, data)

# %% [8] Final Summary
print("\n" + "=" * 60)
print(f"Training complete. Total: {total_time:.1f}s ({total_time/CONFIG['epochs']:.1f}s/epoch)")
print("=" * 60)
evaluate_discrimination(encoder_online, data)
