"""
Geo-JEPA Prototype: MCR² Encoder + Gene Interaction Prior + JEPA Training
==========================================================================
Target hardware: MacBook Air (Apple Silicon, 16-32GB)
Framework:       PyTorch 2.x with MPS backend

Architecture summary:
  Stage 1 - Gene Interaction Prior:  Single sparse attention layer over
                                      expressed "genes" (MNIST pixels)
  Stage 2 - MCR² ReduNet:             L unrolled gradient steps on the
                                      Maximal Coding Rate Reduction objective
  JEPA Loop:  EMA target encoder + predictor MLP trained to predict
              target gene-set embeddings from context gene-set embeddings

Dataset: MNIST proxy with MNAR dropout and fate bifurcation structure
         (generated by build_proxy_dataset.py, loaded from data/)

Usage:
  python build_proxy_dataset.py                    # generate dataset first
  python geo_jepa_mnist.py                         # train with defaults
  python geo_jepa_mnist.py --phase_a_epochs 10     # shorter Phase A
"""

import json
import math
import argparse
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from pathlib import Path
from torch.utils.data import Dataset, DataLoader
from copy import deepcopy

# ──────────────────────────────────────────────────────────────────────────────
# 0.  DEVICE SELECTION
# ──────────────────────────────────────────────────────────────────────────────


def get_device():
    if torch.backends.mps.is_available():
        print("Using Apple Silicon MPS backend")
        return torch.device("mps")
    elif torch.cuda.is_available():
        print("Using CUDA backend")
        return torch.device("cuda")
    else:
        print("Using CPU backend")
        return torch.device("cpu")


# ──────────────────────────────────────────────────────────────────────────────
# 1.  LOAD PROXY DATASET (generated by build_proxy_dataset.py)
#
#     Loads the pre-built .npz file containing homeostatic cells, perturbation
#     cells (5 types x 3 doses), and OOD test cells. This replaces the former
#     inline dataset builder — build_proxy_dataset.py is the single source of
#     truth for dataset generation.
# ──────────────────────────────────────────────────────────────────────────────


def load_proxy_dataset(data_dir: str = "./data"):
    """
    Load pre-built proxy dataset from .npz file.

    Run `python build_proxy_dataset.py` first to generate the dataset.

    Returns a dict with keys:
      'homeostatic'  : (N, gene_dim) normal cells
      'class_labels' : (N,) integer class label per homeostatic cell (0-6)
      'perturbed'    : list of (cells, labels, name) tuples
      'ood_test'     : (cells, labels, name) tuple for OOD evaluation
      'projection'   : (784, gene_dim) projection matrix
      'room_digits'  : list of digit classes [0, 1, 3, 4, 7, 8, 9]
    """
    npz_path = Path(data_dir) / "proxy_dataset.npz"
    meta_path = Path(data_dir) / "proxy_dataset_metadata.json"

    if not npz_path.exists():
        raise FileNotFoundError(
            f"Dataset not found at {npz_path}. "
            "Run first: python build_proxy_dataset.py"
        )

    data = np.load(npz_path)
    with open(meta_path) as f:
        meta = json.load(f)

    # Reconstruct perturbed list in (cells, labels, name) tuple format
    pert_cells = data["perturbation_cells"]
    pert_ids = data["perturbation_ids"]
    pert_strengths = data["perturbation_strengths"]
    pert_names = meta["perturbation_names"]

    perturbed = []
    for pid in sorted(set(pert_ids)):
        for strength in sorted(set(pert_strengths[pert_ids == pid])):
            mask = (pert_ids == pid) & (pert_strengths == strength)
            cells = pert_cells[mask]
            name = f"{pert_names[str(pid)]}_s{strength}"
            labels = np.full(len(cells), pid, dtype=int)
            perturbed.append((cells, labels, name))

    room_digits = meta["room_digits"]
    homeostatic = data["homeostatic_cells"]
    gene_dim = homeostatic.shape[1]

    print(
        f"Dataset loaded: {homeostatic.shape[0]} homeostatic cells, "
        f"{gene_dim}D gene space, ~{100*(homeostatic==0).mean():.0f}% zeros, "
        f"{len(perturbed)} perturbation conditions"
    )

    return {
        "homeostatic": homeostatic,
        "class_labels": data["homeostatic_labels"],
        "perturbed": perturbed,
        "ood_test": (data["ood_cells"], data["ood_labels"], "ood_toward_7"),
        "projection": data["projection_matrix"],
        "room_digits": room_digits,
    }


class CellDataset(Dataset):
    """Wraps a numpy array of cell expression profiles as a PyTorch dataset."""

    def __init__(self, cells: np.ndarray, labels: np.ndarray):
        self.cells = torch.from_numpy(cells).float()
        self.labels = torch.from_numpy(labels).long()

    def __len__(self):
        return len(self.cells)

    def __getitem__(self, idx):
        return self.cells[idx], self.labels[idx]


# ──────────────────────────────────────────────────────────────────────────────
# 2.  MCR² UTILITIES
#
#     The coding rate R(Z, ε) and its gradient are the mathematical core.
#     We use the Woodbury identity to avoid large matrix inversions:
#
#         (I + A A^T / c)^{-1} A  =  A (I + A^T A / c)^{-1} / c
#
#     This swaps an (embed_dim × embed_dim) inversion for an (n × n) inversion
#     when n < embed_dim (small batches). For n > embed_dim we invert directly.
#     Both paths stay on MPS without calling torch.linalg.solve.
# ──────────────────────────────────────────────────────────────────────────────


def coding_rate(Z: torch.Tensor, eps_sq: float = 0.5) -> torch.Tensor:
    """
    R(Z, ε) = (d/2) log det(I + d/(n ε²) Z Z^T)
    Z : (n, d)  — n samples, d dimensions
    Returns scalar.
    """
    n, d = Z.shape
    c = n * eps_sq / d
    # log det via Cholesky (more numerically stable than direct det)
    # (I + ZZ^T/c) = I + ZZ^T/c
    A = torch.eye(n, device=Z.device) + (Z @ Z.T) / c
    # Cholesky: log det A = 2 * sum(log diag(L))
    try:
        L = torch.linalg.cholesky(A)
        logdet = 2.0 * L.diagonal().log().sum()
    except Exception:
        # Fallback: eigenvalue-based (slower but always works)
        eigvals = torch.linalg.eigvalsh(A)
        logdet = eigvals.clamp(min=1e-8).log().sum()
    return (d / 2.0) * logdet


def mcr2_loss(
    Z: torch.Tensor, Pi: torch.Tensor, eps_sq: float = 0.5, gamma: float = 1.0
) -> torch.Tensor:
    """
    MCR² objective: ΔR = R(Z) - Σ_k (n_k/n) R(Z_k)
    We MAXIMIZE this, so the loss is -ΔR.

    Z  : (n, d)  embeddings
    Pi : (n, K)  soft class assignments (rows sum to 1)
    gamma: weight on compression term
    """
    total_rate = coding_rate(Z, eps_sq)

    compression = torch.tensor(0.0, device=Z.device)
    K = Pi.shape[1]
    n = Z.shape[0]
    for k in range(K):
        weights = Pi[:, k]  # (n,)
        n_k = weights.sum().clamp(min=1.0)
        # Weighted Z_k: scale rows by sqrt(weight) so ZZ^T gives weighted covariance
        Z_k = Z * weights.unsqueeze(1).sqrt()  # (n, d)
        # Pass effective count n_k to coding_rate
        rate_k = coding_rate(Z_k * math.sqrt(n / n_k.item()), eps_sq)
        compression = compression + (n_k / n) * rate_k

    delta_r = total_rate - gamma * compression
    return -delta_r, total_rate, compression


# ──────────────────────────────────────────────────────────────────────────────
# 3.  GENE INTERACTION PRIOR (Sparse Attention)
#
#     Single attention layer over *expressed* genes only.
#     "Expressed" = nonzero after dropout. We subsample to max_genes for speed.
#     This is Stage 1 of the encoder.
# ──────────────────────────────────────────────────────────────────────────────


class GeneInteractionPrior(nn.Module):
    """
    Single multi-head attention layer over expressed genes.

    Each expressed gene is a token: (gene_identity_embedding + expression_value).
    We use a fixed vocabulary of gene positions (indices 0..gene_dim-1).

    Input:  x  (batch, gene_dim)   — sparse expression vector
    Output: h  (batch, embed_dim)  — aggregated gene interaction features
    """

    def __init__(
        self, gene_dim: int, embed_dim: int, n_heads: int = 4, max_genes: int = 200
    ):
        super().__init__()
        self.gene_dim = gene_dim
        self.embed_dim = embed_dim
        self.max_genes = max_genes  # cap for speed on MacBook

        # Gene identity embeddings: each gene position gets a learned vector
        self.gene_embed = nn.Embedding(gene_dim, embed_dim)

        # Expression value encoding: scalar → embed_dim via linear
        self.expr_proj = nn.Linear(1, embed_dim)

        # Single attention layer
        self.attn = nn.MultiheadAttention(
            embed_dim, n_heads, batch_first=True, dropout=0.0
        )
        self.norm = nn.LayerNorm(embed_dim)

        # Aggregate variable-length attended tokens → fixed vector
        self.pool_proj = nn.Linear(embed_dim, embed_dim)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        x: (batch, gene_dim)
        Returns: (batch, embed_dim)
        """
        batch_size = x.shape[0]
        device = x.device

        # Find expressed genes (nonzero) per sample — vectorised approximation:
        # Use top-k by expression value instead of strict nonzero for batching
        top_vals, top_idx = x.topk(self.max_genes, dim=1)  # (batch, max_genes)

        # Token = gene identity embedding + expression projection
        gene_id_emb = self.gene_embed(top_idx)  # (batch, G, embed_dim)
        expr_emb = self.expr_proj(top_vals.unsqueeze(-1))  # (batch, G, embed_dim)
        tokens = gene_id_emb + expr_emb  # (batch, G, embed_dim)

        # Mask for truly zero genes (top_val == 0 → padding)
        key_padding_mask = top_vals == 0  # (batch, G)

        # Self-attention over expressed gene tokens
        attended, _ = self.attn(
            tokens, tokens, tokens, key_padding_mask=key_padding_mask
        )
        attended = self.norm(attended + tokens)  # residual

        # Mean pooling over expressed genes (ignore padding)
        valid = (~key_padding_mask).float().unsqueeze(-1)  # (batch, G, 1)
        pooled = (attended * valid).sum(dim=1) / valid.sum(dim=1).clamp(min=1)
        # (batch, embed_dim)

        return self.pool_proj(pooled)


# ──────────────────────────────────────────────────────────────────────────────
# 4.  MCR² ReduNet ENCODER (Stage 2)
#
#     L unrolled gradient steps on ΔR.
#     Each step = one "expansion" move + one "compression" move.
#     The class assignments Π are estimated online from current embeddings.
# ──────────────────────────────────────────────────────────────────────────────


class ReduNetLayer(nn.Module):
    """
    One unrolled MCR² gradient step.
    Operates on a batch Z ∈ (n, d) and soft assignments Pi ∈ (n, K).

    Z^(ℓ+1) = Z^(ℓ) + η (E Z^(ℓ) - Σ_k (n_k/n) C_k Z_k^(ℓ))

    E  = (I + ZZ^T / (n ε²/d))^{-1}   [expansion: push apart globally]
    C_k = (I + Z_k Z_k^T / (n_k ε²/d))^{-1}  [compression: squeeze per class]

    We compute E·Z via the Woodbury identity to stay numerically stable.
    """

    def __init__(
        self,
        embed_dim: int,
        n_classes: int,
        eps_sq: float = 0.5,
        step_size: float = 0.5,
    ):
        super().__init__()
        self.d = embed_dim
        self.K = n_classes
        self.eps_sq = eps_sq
        self.eta = step_size
        # Learnable per-layer step size (allows the network to adapt)
        self.log_eta = nn.Parameter(torch.tensor(math.log(step_size)))

    def _woodbury_mv(self, Z: torch.Tensor, c: float) -> torch.Tensor:
        """
        Compute (I + ZZ^T/c)^{-1} Z  efficiently.

        By Woodbury:  (I + ZZ^T/c)^{-1} Z = Z (I + Z^T Z/c)^{-1} / c...
        wait, let's use the direct form that's stable:

        (I_n + ZZ^T/c)^{-1} Z  via solving a (n×n) system when n < d,
        or direct (d×d) solve when d < n.
        We avoid torch.linalg.solve on MPS (can be buggy); use
        Cholesky + triangular solve instead.
        """
        n, d = Z.shape
        eta = self.log_eta.exp()

        if n <= d:
            # Solve via n×n system: A v = Z where A = I_n + ZZ^T/c
            A = torch.eye(n, device=Z.device, dtype=Z.dtype) + Z @ Z.T / c
            # Cholesky factorization (A is symmetric positive definite)
            L = torch.linalg.cholesky(A)
            # (I + ZZ^T/c)^{-1} Z  =  L^{-T} (L^{-1} Z)
            EZ = torch.cholesky_solve(Z, L)
        else:
            # Solve via d×d system: more efficient when d < n
            A = torch.eye(d, device=Z.device, dtype=Z.dtype) + Z.T @ Z / c
            L = torch.linalg.cholesky(A)
            # (I + Z^T Z/c)^{-1} Z^T  then transpose
            EZ = (torch.cholesky_solve(Z.T, L)).T / c
            # Actually: (I + ZZ^T/c)^{-1} Z = Z(I + Z^TZ/c)^{-1}/c
            # Let's redo:
            # Sherman-Morrison-Woodbury:
            # (I + ZZ^T/c)^{-1} = I - Z(cI + Z^TZ)^{-1}Z^T
            # so (I + ZZ^T/c)^{-1}Z = Z - Z(cI + Z^TZ)^{-1}Z^TZ
            cI_ZtZ = c * torch.eye(d, device=Z.device) + Z.T @ Z
            L2 = torch.linalg.cholesky(cI_ZtZ)
            inner = torch.cholesky_solve(Z.T @ Z, L2)  # (d, d)
            EZ = Z - Z @ inner

        return EZ * eta

    def forward(self, Z: torch.Tensor, Pi: torch.Tensor) -> torch.Tensor:
        """
        Z  : (n, d)
        Pi : (n, K) soft class assignments, rows sum to ~1
        Returns updated Z : (n, d)
        """
        n, d = Z.shape
        c_global = n * self.eps_sq / d

        # Expansion term: E Z
        expansion = self._woodbury_mv(Z, c_global)

        # Compression term: Σ_k (n_k/n) C_k Z_k
        compression = torch.zeros_like(Z)
        for k in range(self.K):
            w_k = Pi[:, k]  # (n,)
            n_k = w_k.sum().clamp(min=1.0)
            Z_k = Z * w_k.unsqueeze(1)  # weighted
            c_k = n_k * self.eps_sq / d
            C_k_Z_k = self._woodbury_mv(Z_k * math.sqrt(n / n_k.item()), c_k)
            C_k_Z_k = C_k_Z_k / max(math.sqrt(n / n_k.item()), 1.0)
            compression = compression + (n_k / n) * C_k_Z_k

        Z_next = Z + expansion - compression
        return Z_next


class ReduNetEncoder(nn.Module):
    """
    Full MCR² ReduNet encoder: linear lift + L gradient steps.

    Input:  h (batch, input_dim)   — output from GeneInteractionPrior
    Output: z (batch, embed_dim)   — normalized embedding
    """

    def __init__(
        self,
        input_dim: int,
        embed_dim: int,
        n_classes: int,
        n_layers: int = 6,
        eps_sq: float = 0.5,
    ):
        super().__init__()
        self.embed_dim = embed_dim
        self.n_classes = n_classes

        # Linear lift: input_dim → embed_dim
        self.lift = nn.Linear(input_dim, embed_dim, bias=False)
        nn.init.orthogonal_(self.lift.weight)

        # L unrolled MCR² layers
        self.layers = nn.ModuleList(
            [ReduNetLayer(embed_dim, n_classes, eps_sq=eps_sq) for _ in range(n_layers)]
        )

    def estimate_assignments(self, Z: torch.Tensor) -> torch.Tensor:
        """
        Online soft clustering: assign each embedding to nearest centroid.
        Centroids are estimated from current batch (no stored state).
        Returns Pi : (n, K) with rows summing to 1.
        """
        n, d = Z.shape
        K = self.n_classes

        if n < K:
            # Not enough samples: uniform assignment
            return torch.full((n, K), 1.0 / K, device=Z.device)

        # K-means style soft assignment with temperature
        Z_norm = F.normalize(Z, dim=1)

        # Initialize centroids with k-means++ style seeding (deterministic)
        idx = torch.randperm(n, device=Z.device)[:K]
        centroids = Z_norm[idx]  # (K, d)

        # 2 iterations of soft assignment update (enough for intra-batch)
        for _ in range(2):
            # Cosine similarity: (n, K)
            sims = Z_norm @ centroids.T
            Pi = F.softmax(sims * 5.0, dim=1)  # temperature = 5.0
            # Update centroids as weighted means
            centroids = F.normalize(Pi.T @ Z_norm, dim=1)  # (K, d)

        return Pi

    def forward(self, h: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """
        Returns:
          z   : (n, embed_dim) normalized final embedding
          Pi  : (n, K) soft assignments from last layer (for loss)
        """
        Z = self.lift(h)  # (n, embed_dim)

        for layer in self.layers:
            Pi = self.estimate_assignments(
                Z.detach()
            )  # detach: Pi is not differentiated
            Z = layer(Z, Pi)

        Pi_final = self.estimate_assignments(Z.detach())
        z = F.normalize(Z, dim=1)
        return z, Pi_final


# ──────────────────────────────────────────────────────────────────────────────
# 5.  FULL ENCODER (Stage 1 + Stage 2)
# ──────────────────────────────────────────────────────────────────────────────


class GeoJEPAEncoder(nn.Module):
    """
    Complete Geo-JEPA encoder:
      Stage 1: GeneInteractionPrior (sparse attention)
      Stage 2: ReduNetEncoder (MCR² gradient steps)
    """

    def __init__(
        self,
        gene_dim: int,
        embed_dim: int,
        n_classes: int,
        n_heads: int = 4,
        max_genes: int = 200,
        n_layers: int = 6,
    ):
        super().__init__()
        self.prior = GeneInteractionPrior(
            gene_dim, embed_dim, n_heads=n_heads, max_genes=max_genes
        )
        self.redu = ReduNetEncoder(embed_dim, embed_dim, n_classes, n_layers=n_layers)

    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        h = self.prior(x)  # (n, embed_dim)
        z, Pi = self.redu(h)  # (n, embed_dim), (n, K)
        return z, Pi


# ──────────────────────────────────────────────────────────────────────────────
# 6.  PREDICTOR (small MLP, fate-conditional)
#
#     Given context embedding z_C and soft assignment Pi,
#     predict target embedding z_T.
#
#     Fate-conditioning: the predictor receives the soft assignment
#     as an extra input, forcing it to commit to a subspace before predicting.
# ──────────────────────────────────────────────────────────────────────────────


class FateConditionalPredictor(nn.Module):
    """
    MLP predictor: (z_C, Pi) → ẑ_T

    The assignment vector Pi acts as a "gate" — the predictor sees
    which subspace the context embedding belongs to before predicting
    where the target embedding lives.
    """

    def __init__(self, embed_dim: int, n_classes: int, hidden_dim: int = 256):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(embed_dim + n_classes, hidden_dim),
            nn.GELU(),
            nn.LayerNorm(hidden_dim),
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, embed_dim),
        )

    def forward(self, z_C: torch.Tensor, Pi: torch.Tensor) -> torch.Tensor:
        inp = torch.cat([z_C, Pi], dim=1)
        z_hat = self.net(inp)
        return F.normalize(z_hat, dim=1)


# ──────────────────────────────────────────────────────────────────────────────
# 7.  GENE-SET MASKING (the scRNA-seq analog of spatial patch masking)
#
#     Partition the gene dimension into context and target subsets.
#     We mask by setting target-gene values to zero in the context,
#     and context-gene values to zero in the target.
# ──────────────────────────────────────────────────────────────────────────────


def gene_set_mask(
    x: torch.Tensor, context_ratio: float = 0.75
) -> tuple[torch.Tensor, torch.Tensor]:
    """
    Randomly partition gene indices into context (visible) and target (masked).

    x           : (batch, gene_dim)
    context_ratio: fraction of genes visible to context encoder

    Returns:
      x_context  : (batch, gene_dim)  — target genes zeroed out
      x_target   : (batch, gene_dim)  — context genes zeroed out
    """
    gene_dim = x.shape[1]
    n_context = int(gene_dim * context_ratio)

    # Random permutation of gene indices (same for whole batch for simplicity)
    perm = torch.randperm(gene_dim, device=x.device)
    context_idx = perm[:n_context]
    target_idx = perm[n_context:]

    x_context = torch.zeros_like(x)
    x_context[:, context_idx] = x[:, context_idx]

    x_target = torch.zeros_like(x)
    x_target[:, target_idx] = x[:, target_idx]

    return x_context, x_target


# ──────────────────────────────────────────────────────────────────────────────
# 8.  EMA UPDATE
# ──────────────────────────────────────────────────────────────────────────────


@torch.no_grad()
def ema_update(online: nn.Module, target: nn.Module, momentum: float = 0.999):
    """Update target encoder as exponential moving average of online encoder."""
    for p_online, p_target in zip(online.parameters(), target.parameters()):
        p_target.data.mul_(momentum).add_(p_online.data, alpha=1.0 - momentum)


# ──────────────────────────────────────────────────────────────────────────────
# 9.  TRAINING LOOP
# ──────────────────────────────────────────────────────────────────────────────


def _run_epoch(
    encoder_online,
    encoder_target,
    predictor,
    loader,
    optimizer,
    config,
    device,
    anchor_embeddings=None,
):
    """Run one training epoch. Returns (avg_pred_loss, avg_mcr_loss, avg_anchor_loss)."""
    encoder_online.train()
    predictor.train()

    epoch_pred_loss = 0.0
    epoch_mcr_loss = 0.0
    epoch_anchor_loss = 0.0
    n_batches = 0
    params = list(encoder_online.parameters()) + list(predictor.parameters())

    for x_batch, labels in loader:
        x_batch = x_batch.to(device)

        # --- Gene-set masking ---
        x_context, x_target = gene_set_mask(
            x_batch, context_ratio=config["context_ratio"]
        )

        # --- Online encoder: process context genes ---
        z_C, Pi_C = encoder_online(x_context)

        # --- Target encoder: process target genes (stop gradient) ---
        with torch.no_grad():
            z_T, _ = encoder_target(x_target)

        # --- Predictor: predict target embedding from context ---
        z_hat_T = predictor(z_C, Pi_C)

        # --- Losses ---
        # 1. JEPA prediction loss
        pred_loss = F.mse_loss(z_hat_T, z_T.detach())

        # 2. MCR² loss on context embeddings
        mcr_loss_val, rate, compression = mcr2_loss(
            z_C, Pi_C, eps_sq=config["eps_sq"], gamma=config["mcr_gamma"]
        )

        loss = pred_loss + config["mcr_weight"] * mcr_loss_val

        # 3. EMA anchor loss (Phase B only)
        anchor_loss_val = 0.0
        if anchor_embeddings is not None:
            # Re-embed the full (unmasked) batch through online encoder
            z_full, _ = encoder_online(x_batch)
            # Look up the frozen anchor embeddings for these homeostatic cells
            # anchor_embeddings is a dict: label -> centroid embedding
            # Compute per-sample anchor loss: pull online embeddings toward
            # their room's frozen anchor centroid
            anchor_targets = torch.stack(
                [anchor_embeddings[lab.item()] for lab in labels]
            )  # (batch, embed_dim)
            a_loss = F.mse_loss(z_full, anchor_targets.detach())
            loss = loss + config["anchor_weight"] * a_loss
            anchor_loss_val = a_loss.item()

        # --- Backward ---
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(params, max_norm=1.0)
        optimizer.step()

        # --- EMA update of target encoder ---
        ema_update(encoder_online, encoder_target, momentum=config["ema_momentum"])

        epoch_pred_loss += pred_loss.item()
        epoch_mcr_loss += mcr_loss_val.item()
        epoch_anchor_loss += anchor_loss_val
        n_batches += 1

    return (
        epoch_pred_loss / n_batches,
        epoch_mcr_loss / n_batches,
        epoch_anchor_loss / n_batches,
    )


@torch.no_grad()
def _compute_anchor_embeddings(encoder_target, data, device, n_classes):
    """Compute per-room anchor centroids from the target encoder at end of Phase A.

    Returns dict mapping label (int) -> centroid embedding tensor on device.
    """
    encoder_target.eval()
    anchor = {}
    for label_idx in range(n_classes):
        mask = data["class_labels"] == label_idx
        cells = torch.from_numpy(data["homeostatic"][mask]).float().to(device)
        if len(cells) == 0:
            continue
        embs = []
        for i in range(0, len(cells), 128):
            z, _ = encoder_target(cells[i : i + 128])
            embs.append(z)
        anchor[label_idx] = torch.cat(embs, dim=0).mean(dim=0)  # (embed_dim,)
    return anchor


def train(config: dict):
    device = get_device()

    # --- Load dataset ---
    print("\nLoading proxy dataset...")
    data = load_proxy_dataset(config["data_dir"])

    n_classes = len(data["room_digits"])
    gene_dim = data["homeostatic"].shape[1]
    embed_dim = config["embed_dim"]

    # --- Build models ---
    print(
        f"\nBuilding models: gene_dim={gene_dim}, embed_dim={embed_dim}, "
        f"n_classes={n_classes}"
    )

    encoder_online = GeoJEPAEncoder(
        gene_dim=gene_dim,
        embed_dim=embed_dim,
        n_classes=n_classes,
        n_heads=config["n_heads"],
        max_genes=config["max_genes"],
        n_layers=config["n_layers"],
    ).to(device)

    encoder_target = deepcopy(encoder_online).to(device)
    for p in encoder_target.parameters():
        p.requires_grad_(False)

    predictor = FateConditionalPredictor(
        embed_dim=embed_dim,
        n_classes=n_classes,
        hidden_dim=config["predictor_hidden"],
    ).to(device)

    params = list(encoder_online.parameters()) + list(predictor.parameters())
    n_params = sum(p.numel() for p in params if p.requires_grad)
    print(f"Trainable parameters: {n_params:,}")

    # ================================================================
    # PHASE A: Homeostatic scaffold (train on homeostatic cells only)
    # ================================================================
    print("\n" + "=" * 60)
    print("PHASE A: Homeostatic scaffold training")
    print("=" * 60)

    home_dataset = CellDataset(data["homeostatic"], data["class_labels"])
    home_loader = DataLoader(
        home_dataset,
        batch_size=config["batch_size"],
        shuffle=True,
        num_workers=0,
        pin_memory=False,
    )

    optimizer_a = torch.optim.AdamW(
        params, lr=config["lr"], weight_decay=config["weight_decay"]
    )
    scheduler_a = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer_a, T_max=config["phase_a_epochs"]
    )

    best_pred_loss = float("inf")
    patience_counter = 0
    phase_a_actual = 0

    for epoch in range(1, config["phase_a_epochs"] + 1):
        avg_pred, avg_mcr, _ = _run_epoch(
            encoder_online,
            encoder_target,
            predictor,
            home_loader,
            optimizer_a,
            config,
            device,
            anchor_embeddings=None,
        )
        scheduler_a.step()
        phase_a_actual = epoch

        if epoch % config["log_every"] == 0 or epoch == 1:
            lr_now = scheduler_a.get_last_lr()[0]
            print(
                f"[A] Epoch {epoch:3d}/{config['phase_a_epochs']} | "
                f"pred_loss={avg_pred:.4f} | "
                f"mcr_loss={avg_mcr:.4f} | "
                f"lr={lr_now:.2e}"
            )

        # Plateau detection
        if avg_pred < best_pred_loss - config["phase_a_min_delta"]:
            best_pred_loss = avg_pred
            patience_counter = 0
        else:
            patience_counter += 1

        if patience_counter >= config["phase_a_patience"]:
            print(
                f"[A] pred_loss plateaued for {config['phase_a_patience']} epochs "
                f"(best={best_pred_loss:.4f}). Transitioning to Phase B."
            )
            break

    if patience_counter < config["phase_a_patience"]:
        print(f"[A] Completed all {config['phase_a_epochs']} Phase A epochs.")

    # --- Freeze anchor embeddings from target encoder ---
    print("\nComputing anchor embeddings from target encoder...")
    anchor_embeddings = _compute_anchor_embeddings(
        encoder_target, data, device, n_classes
    )
    print(f"  Anchored {len(anchor_embeddings)} room centroids.")

    # --- Intermediate evaluation ---
    print("\n[A] Phase A discrimination check:")
    evaluate_discrimination(encoder_online, data, device)

    # ================================================================
    # PHASE B: Perturbation learning with EMA anchor
    # ================================================================
    print("\n" + "=" * 60)
    print("PHASE B: Perturbation learning with EMA anchor")
    print("=" * 60)

    # Build combined dataset: homeostatic + perturbation cells
    # Perturbation cells get a source-room label for the anchor loss
    pert_cells_list = []
    pert_labels_list = []
    for cells, labels, name in data["perturbed"]:
        pert_cells_list.append(cells)
        # Labels here are pert_ids; we need source room labels for anchor loss.
        # Fate perturbations (pert_id 0,1) start from progenitor (digit 9 = label 6).
        # We assign them the progenitor room label so the anchor loss
        # keeps them tethered to the progenitor geometry initially.
        progenitor_label = data["room_digits"].index(9)
        pert_labels_list.append(np.full(len(cells), progenitor_label, dtype=np.int64))

    all_cells = np.concatenate([data["homeostatic"]] + pert_cells_list, axis=0)
    all_labels = np.concatenate(
        [data["class_labels"].astype(np.int64)] + pert_labels_list, axis=0
    )

    combined_dataset = CellDataset(all_cells, all_labels)
    combined_loader = DataLoader(
        combined_dataset,
        batch_size=config["batch_size"],
        shuffle=True,
        num_workers=0,
        pin_memory=False,
    )

    # Fresh optimizer with lower LR for Phase B
    optimizer_b = torch.optim.AdamW(
        params, lr=config["phase_b_lr"], weight_decay=config["weight_decay"]
    )
    scheduler_b = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer_b, T_max=config["phase_b_epochs"]
    )

    for epoch in range(1, config["phase_b_epochs"] + 1):
        avg_pred, avg_mcr, avg_anchor = _run_epoch(
            encoder_online,
            encoder_target,
            predictor,
            combined_loader,
            optimizer_b,
            config,
            device,
            anchor_embeddings=anchor_embeddings,
        )
        scheduler_b.step()

        if epoch % config["log_every"] == 0 or epoch == 1:
            lr_now = scheduler_b.get_last_lr()[0]
            print(
                f"[B] Epoch {epoch:3d}/{config['phase_b_epochs']} | "
                f"pred_loss={avg_pred:.4f} | "
                f"mcr_loss={avg_mcr:.4f} | "
                f"anchor_loss={avg_anchor:.4f} | "
                f"lr={lr_now:.2e}"
            )

    total_epochs = phase_a_actual + config["phase_b_epochs"]
    print(
        f"\nTraining complete. Phase A: {phase_a_actual} epochs, "
        f"Phase B: {config['phase_b_epochs']} epochs, total: {total_epochs}"
    )

    # --- Final evaluation ---
    print("\n[B] Final discrimination ratio on 4/9 bifurcation:")
    evaluate_discrimination(encoder_online, data, device)

    return encoder_online, encoder_target, predictor, data


# ──────────────────────────────────────────────────────────────────────────────
# 10. EVALUATION: DISCRIMINATION RATIO
#
#     The key geometric test from the original plan.
#     For a progenitor cell (4/9 blend) under a fate-A perturbation,
#     is the predicted embedding closer to the fate-A room than fate-B?
#
#     Discrimination Ratio = dist(ẑ → wrong_fate) / dist(ẑ → correct_fate)
#     Target: > 2.0 (prediction is at least 2x closer to the right fate)
# ──────────────────────────────────────────────────────────────────────────────


@torch.no_grad()
def evaluate_discrimination(encoder: nn.Module, data: dict, device: torch.device):
    encoder.eval()

    # Get embeddings for homeostatic rooms
    room_embeddings = {}
    for label_idx, digit in enumerate(data["room_digits"]):
        mask = data["class_labels"] == label_idx
        cells = torch.from_numpy(data["homeostatic"][mask]).float().to(device)
        if len(cells) == 0:
            continue
        # Process in small batches to avoid OOM
        embs = []
        for i in range(0, len(cells), 128):
            z, _ = encoder(cells[i : i + 128])
            embs.append(z)
        room_embeddings[digit] = torch.cat(embs, dim=0).mean(dim=0)  # centroid

    # Evaluate fate-A perturbation (toward digit 4) starting from digit 9
    fate_A_cells = None
    for cells, labels, name in data["perturbed"]:
        if "fate_A" in name and "s1.0" in name:
            fate_A_cells = torch.from_numpy(cells).float().to(device)
            break

    if fate_A_cells is None or 4 not in room_embeddings or 1 not in room_embeddings:
        print("Could not evaluate: missing perturbation data or room embeddings")
        return

    # Embed the fate-A perturbed cells (progenitor → fate 4)
    embs = []
    for i in range(0, min(len(fate_A_cells), 256), 128):
        z, _ = encoder(fate_A_cells[i : i + 128])
        embs.append(z)
    z_pert = torch.cat(embs, dim=0).mean(dim=0)

    # Centroid of fate-A room (digit 4) and fate-B room (digit 1)
    c_fate_A = room_embeddings[4]  # correct destination
    c_fate_B = room_embeddings[1]  # wrong destination

    dist_correct = (z_pert - c_fate_A).norm().item()
    dist_wrong = (z_pert - c_fate_B).norm().item()
    ratio = dist_wrong / (dist_correct + 1e-8)

    print(f"  dist(predicted → fate_A room): {dist_correct:.4f}")
    print(f"  dist(predicted → fate_B room): {dist_wrong:.4f}")
    print(f"  Discrimination Ratio:          {ratio:.2f}x")
    if ratio > 2.0:
        print("  ✓ PASSED: Linearization Trap avoided (ratio > 2.0)")
    elif ratio > 1.0:
        print("  ~ PARTIAL: Correct direction but not strongly discriminated")
    else:
        print("  ✗ FAILED: Model cannot discriminate fate outcomes")


# ──────────────────────────────────────────────────────────────────────────────
# 11. MAIN
# ──────────────────────────────────────────────────────────────────────────────

DEFAULT_CONFIG = {
    # Dataset
    "data_dir": "./data",
    # Architecture
    "embed_dim": 128,
    "n_heads": 4,
    "max_genes": 200,  # genes per attention layer (speed limit)
    "n_layers": 6,  # ReduNet layers
    "predictor_hidden": 256,
    # JEPA
    "context_ratio": 0.75,  # fraction of genes visible to context encoder
    "ema_momentum": 0.999,
    # Loss
    "mcr_weight": 0.1,  # weight on MCR² loss relative to prediction
    "mcr_gamma": 1.0,  # expansion/compression balance in MCR²
    "eps_sq": 0.5,  # ε² in coding rate formula
    # Training
    "batch_size": 128,
    "lr": 3e-4,
    "weight_decay": 1e-4,
    "log_every": 1,
    # Phase A/B curriculum
    "phase_a_epochs": 20,  # max epochs for Phase A (homeostatic only)
    "phase_a_patience": 5,  # plateau detection: switch after this many epochs w/o improvement
    "phase_a_min_delta": 1e-4,  # minimum pred_loss decrease to count as improvement
    "phase_b_epochs": 20,  # epochs for Phase B (perturbation + anchor)
    "anchor_weight": 0.5,  # weight on EMA anchor loss in Phase B
    "phase_b_lr": 1e-4,  # lower LR for Phase B fine-tuning
}


def main():
    parser = argparse.ArgumentParser(description="Geo-JEPA MNIST Proxy")
    for k, v in DEFAULT_CONFIG.items():
        t = type(v)
        parser.add_argument(f"--{k}", type=t, default=v)
    args = parser.parse_args()
    config = vars(args)

    print("=" * 60)
    print("Geo-JEPA Prototype: MCR² + Gene Interaction Prior")
    print("=" * 60)
    print(
        f"Config: embed_dim={config['embed_dim']}, "
        f"n_layers={config['n_layers']}, "
        f"data_dir={config['data_dir']}, "
        f"batch_size={config['batch_size']}"
    )
    print(
        f"Curriculum: Phase A up to {config['phase_a_epochs']} epochs "
        f"(patience={config['phase_a_patience']}), "
        f"Phase B {config['phase_b_epochs']} epochs "
        f"(anchor_weight={config['anchor_weight']})"
    )

    train(config)


if __name__ == "__main__":
    main()
