"""
LeWM-scRNA: World Model for Single-Cell Perturbation Prediction
================================================================
Inspired by LeWorldModel (le-wm.github.io), treats perturbations as "actions"
in a latent world model. Uses SIGReg (Sketched-Isotropic-Gaussian Regularizer)
instead of MCR² for unsupervised collapse prevention.

Phase 1 — Homeostatic Structure:
  MLP encoder with BatchNorm projector (no L2 norm) + JEPA gene-set masking.
  SIGReg enforces isotropic Gaussian embeddings via Epps-Pulley test on
  random 1D projections (Cramér-Wold theorem). No EMA target encoder needed.

Phase 2 — Perturbation Prediction (World Model):
  AdaLN-conditioned transformer predictor maps (z_cell, a_perturbation) -> z_post.
  Perturbations = actions. Encoder trained jointly (not frozen) with SIGReg
  preventing collapse. Zero-initialized AdaLN starts as identity, learns deviations.

Dataset: MNIST proxy (generated by build_proxy_dataset.py)
Output: results/lewm/
"""

# %% [1] Imports & Setup
import json
import time
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib
matplotlib.use("Agg")  # non-blocking: save to file, no GUI window
import matplotlib.pyplot as plt
import umap
from pathlib import Path
from torch.utils.data import Dataset, DataLoader

DEVICE = torch.device(
    "mps" if torch.backends.mps.is_available()
    else "cuda" if torch.cuda.is_available()
    else "cpu"
)
print(f"Using device: {DEVICE}")

# %% [2] Configuration
CONFIG = {
    "data_dir":         "./data",
    "embed_dim":        128,
    "hidden_dim":       512,
    "predictor_hidden": 256,
    "context_ratio":    0.75,
    "sigreg_weight":    1.0,
    "sigreg_projs":     64,       # number of random projections for SIGReg
    "batch_size":       512,
    "epochs":           40,
    "lr":               1e-3,
    "weight_decay":     1e-4,
    "diag_every":       10,
    # Phase 2: perturbation prediction
    "phase2_epochs":    40,
    "phase2_lr":        3e-4,
    "phase2_encoder_lr": 1e-4,   # lower LR for encoder during joint training
    "pert_embed_dim":   32,
    "n_pert_types":     5,
    "adaln_layers":     4,
    "adaln_heads":      4,
}

TRAIN_DIR = Path("results/lewm")
TRAIN_DIR.mkdir(parents=True, exist_ok=True)
METRICS_LOG = TRAIN_DIR / "metrics.jsonl"
print(f"Training output: {TRAIN_DIR}")


def log_metrics(**kwargs):
    with open(METRICS_LOG, "a") as f:
        f.write(json.dumps(kwargs) + "\n")


# %% [3] Dataset (reused from geo_jepa_simple.py)
def load_proxy_dataset(data_dir: str = "./data"):
    npz_path = Path(data_dir) / "proxy_dataset.npz"
    meta_path = Path(data_dir) / "proxy_dataset_metadata.json"

    if not npz_path.exists():
        raise FileNotFoundError(
            f"Dataset not found at {npz_path}. "
            "Run first: python build_proxy_dataset.py"
        )

    data = np.load(npz_path)
    with open(meta_path) as f:
        meta = json.load(f)

    pert_cells = data["perturbation_cells"]
    pert_ids = data["perturbation_ids"]
    pert_strengths = data["perturbation_strengths"]
    pert_labels = data["perturbation_labels"]
    pert_names = meta["perturbation_names"]

    perturbed = []
    for pid in sorted(set(pert_ids)):
        for strength in sorted(set(pert_strengths[pert_ids == pid])):
            mask = (pert_ids == pid) & (pert_strengths == strength)
            cells = pert_cells[mask]
            name = f"{pert_names[str(pid)]}_s{strength}"
            labels = np.full(len(cells), pid, dtype=int)
            perturbed.append((cells, labels, name))

    homeostatic = data["homeostatic_cells"]
    gene_dim = homeostatic.shape[1]
    print(f"Dataset loaded: {homeostatic.shape[0]} homeostatic, "
          f"{gene_dim}D, ~{100*(homeostatic==0).mean():.0f}% zeros")

    return {
        "homeostatic": homeostatic,
        "class_labels": data["homeostatic_labels"],
        "perturbed": perturbed,
        "pert_cells": pert_cells,
        "pert_ids": pert_ids,
        "pert_strengths": pert_strengths,
        "pert_labels": pert_labels,
        "ood_test": (data["ood_cells"], data["ood_labels"], "ood_toward_7"),
        "room_digits": meta["room_digits"],
        "fate_destinations": meta.get("fate_destinations", {}),
    }


class CellDataset(Dataset):
    def __init__(self, cells: np.ndarray, labels: np.ndarray):
        self.cells = torch.from_numpy(cells).float()
        self.labels = torch.from_numpy(labels).long()

    def __len__(self):
        return len(self.cells)

    def __getitem__(self, idx):
        return self.cells[idx], self.labels[idx]


# %% [4] SIGReg Loss — Sketched Isotropic Gaussian Regularizer
#
# Projects embeddings onto K random unit directions, tests each 1D projection
# for Gaussianity via the Epps-Pulley statistic. Cramér-Wold theorem:
# if all 1D marginals are Gaussian, the joint distribution is Gaussian.
# This prevents representation collapse without EMA or stop-gradient tricks.

def epps_pulley_statistic(x: torch.Tensor) -> torch.Tensor:
    """Epps-Pulley test statistic for Gaussianity of a 1D sample.

    Lower values = more Gaussian. Returns a scalar loss.

    x: (n,) 1D tensor of samples, assumed already zero-mean.
    """
    n = x.shape[0]
    var = x.var() + 1e-8

    # Term 1: pairwise interactions
    # (2/n²) Σ_{i<j} exp(-||x_i - x_j||² / (4σ²))
    # Efficient: use broadcasting. Full matrix then halve.
    diffs_sq = (x.unsqueeze(0) - x.unsqueeze(1)) ** 2  # (n, n)
    T1 = torch.exp(-diffs_sq / (4.0 * var)).sum() / (n * n)

    # Term 2: individual terms
    # -(2/n)(1 + 2σ²)^{-1/2} Σ_i exp(-x_i² / (2 + 4σ²))
    scale2 = 1.0 + 2.0 * var
    T2 = -2.0 * (scale2 ** -0.5) * torch.exp(-x ** 2 / (2.0 * scale2)).mean()

    # Term 3: constant
    T3 = (1.0 + 4.0 * var) ** -0.5

    return T1 + T2 + T3


def sigreg_loss(Z: torch.Tensor, n_projections: int = 64,
                _directions: dict = {}) -> torch.Tensor:
    """SIGReg: aggregate Epps-Pulley over random 1D projections.

    Z: (batch_size, embed_dim) embeddings
    Returns: scalar loss (lower = more Gaussian = less collapse)
    """
    d = Z.shape[1]
    key = (d, Z.device.type)

    # Cache random directions (fixed across training for stability)
    if key not in _directions or _directions[key].shape[0] != n_projections:
        dirs = torch.randn(n_projections, d, device=Z.device)
        dirs = F.normalize(dirs, dim=1)
        _directions[key] = dirs

    directions = _directions[key].to(Z.device)
    projections = Z @ directions.T  # (n, K)

    # Standardize each projection to zero mean
    projections = projections - projections.mean(dim=0, keepdim=True)

    total = torch.tensor(0.0, device=Z.device)
    for k in range(n_projections):
        total = total + epps_pulley_statistic(projections[:, k])

    return total / n_projections


# %% [5] Models

class MLPEncoder(nn.Module):
    """MLP encoder with BatchNorm projector (no L2 normalization).

    SIGReg targets isotropic Gaussian in R^d, not on the unit sphere.
    """
    def __init__(self, gene_dim, embed_dim, hidden_dim=512):
        super().__init__()
        self.backbone = nn.Sequential(
            nn.Linear(gene_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, embed_dim),
        )
        # Projector: 1-layer MLP + BatchNorm (matches LeWM design)
        self.projector = nn.Sequential(
            nn.Linear(embed_dim, embed_dim),
            nn.BatchNorm1d(embed_dim),
        )

    def forward(self, x):
        h = self.backbone(x)
        return self.projector(h)


class JEPAPredictor(nn.Module):
    """MLP predictor: z_context -> z_target_hat.
    No perturbation conditioning — just gene-set masking prediction.
    """
    def __init__(self, embed_dim, hidden_dim=256):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(embed_dim, hidden_dim),
            nn.GELU(),
            nn.LayerNorm(hidden_dim),
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, embed_dim),
        )

    def forward(self, z):
        return self.net(z)


class AdaLNBlock(nn.Module):
    """Transformer block with Adaptive Layer Normalization (AdaLN).

    Action (perturbation) information modulates the hidden state via learned
    scale/shift applied after LayerNorm. Zero-initialized so the block starts
    as identity-like: "predict no change, learn deviations."
    """
    def __init__(self, embed_dim, n_heads, action_dim):
        super().__init__()
        self.norm1 = nn.LayerNorm(embed_dim)
        self.attn = nn.MultiheadAttention(embed_dim, n_heads, batch_first=True)
        self.norm2 = nn.LayerNorm(embed_dim)
        self.mlp = nn.Sequential(
            nn.Linear(embed_dim, embed_dim * 4),
            nn.GELU(),
            nn.Linear(embed_dim * 4, embed_dim),
        )
        # AdaLN: action -> (scale1, shift1, scale2, shift2)
        self.adaln = nn.Sequential(
            nn.Linear(action_dim, embed_dim * 4),
        )
        # Zero-init so perturbation has no effect at start
        nn.init.zeros_(self.adaln[0].weight)
        nn.init.zeros_(self.adaln[0].bias)

    def forward(self, x, action_emb):
        """x: (B, embed_dim), action_emb: (B, action_dim)"""
        params = self.adaln(action_emb)  # (B, 4*embed_dim)
        s1, b1, s2, b2 = params.chunk(4, dim=-1)

        # Self-attention with AdaLN modulation
        h = self.norm1(x)
        h = h * (1 + s1) + b1
        h = h.unsqueeze(1)  # (B, 1, D) for MHA
        h, _ = self.attn(h, h, h)
        h = h.squeeze(1)
        x = x + h

        # MLP with AdaLN modulation
        h = self.norm2(x)
        h = h * (1 + s2) + b2
        h = self.mlp(h)
        x = x + h

        return x


class PerturbationPredictor(nn.Module):
    """World model predictor: given z_source and perturbation action, predict z_post.

    Uses AdaLN-conditioned transformer blocks (from LeWM). Zero-initialized
    action conditioning means the predictor starts as near-identity and
    gradually learns how each perturbation shifts the representation.
    """
    def __init__(self, embed_dim, n_pert_types=5, pert_embed_dim=32,
                 n_layers=4, n_heads=4):
        super().__init__()
        action_dim = pert_embed_dim + 1  # pert embedding + dose scalar
        self.pert_embed = nn.Embedding(n_pert_types, pert_embed_dim)
        self.action_proj = nn.Sequential(
            nn.Linear(action_dim, embed_dim),
            nn.GELU(),
            nn.Linear(embed_dim, embed_dim),
        )
        self.blocks = nn.ModuleList([
            AdaLNBlock(embed_dim, n_heads, embed_dim)
            for _ in range(n_layers)
        ])
        self.out_norm = nn.LayerNorm(embed_dim)

    def forward(self, z_source, pert_id, dose):
        """
        z_source: (B, embed_dim) — encoded source cell
        pert_id:  (B,) int — perturbation type
        dose:     (B,) float — strength 0.3/0.6/1.0
        """
        pe = self.pert_embed(pert_id)  # (B, pert_embed_dim)
        action = torch.cat([pe, dose.unsqueeze(1)], dim=1)  # (B, pert_embed_dim+1)
        action_emb = self.action_proj(action)  # (B, embed_dim)

        x = z_source
        for block in self.blocks:
            x = block(x, action_emb)
        return self.out_norm(x)


def gene_set_mask(x, context_ratio=0.75):
    """Partition genes into context (visible) and target (masked)."""
    gene_dim = x.shape[1]
    n_context = int(gene_dim * context_ratio)
    perm = torch.randperm(gene_dim, device=x.device)
    x_context = torch.zeros_like(x)
    x_context[:, perm[:n_context]] = x[:, perm[:n_context]]
    x_target = torch.zeros_like(x)
    x_target[:, perm[n_context:]] = x[:, perm[n_context:]]
    return x_context, x_target


# %% [6] Diagnostic utilities

def coding_rate(Z: torch.Tensor, eps: float = 0.5) -> torch.Tensor:
    """R(Z, eps) = (d/2) log det(I + d/(n*eps^2) Z^T Z).
    Used as a diagnostic metric only, not a loss.
    """
    n, d = Z.shape
    alpha = d / (n * eps ** 2)
    M = torch.eye(d, device=Z.device) + alpha * (Z.T @ Z)
    if M.device.type == "mps":
        eigvals = torch.linalg.eigvalsh(M.cpu()).to(Z.device)
    else:
        eigvals = torch.linalg.eigvalsh(M)
    return 0.5 * torch.sum(torch.log(eigvals.clamp(min=1e-7)))


@torch.no_grad()
def compute_diagnostics(encoder, data, epoch):
    """UMAP + orthogonality heatmap + coding rates. Labels used for evaluation only."""
    encoder.eval()

    cells = torch.from_numpy(data["homeostatic"]).float().to(DEVICE)
    labels = data["class_labels"]
    room_digits = data["room_digits"]
    all_z = []
    for i in range(0, len(cells), 256):
        all_z.append(encoder(cells[i:i+256]).cpu())
    Z = torch.cat(all_z, dim=0).numpy()
    n_cls = len(room_digits)

    # Orthogonality matrix (cosine similarity between room centroids)
    centroids = np.zeros((n_cls, Z.shape[1]))
    for k in range(n_cls):
        mask = labels == k
        if mask.sum() > 0:
            centroids[k] = Z[mask].mean(axis=0)
    norms = np.linalg.norm(centroids, axis=1, keepdims=True) + 1e-8
    centroids_norm = centroids / norms
    ortho = centroids_norm @ centroids_norm.T

    # Per-class coding rates
    Z_tensor = torch.from_numpy(Z).float()
    R_total = coding_rate(Z_tensor, eps=0.5).item()
    class_rates = []
    for k in range(n_cls):
        mask = labels == k
        if mask.sum() >= 2:
            class_rates.append((room_digits[k], coding_rate(Z_tensor[mask], eps=0.5).item(), int(mask.sum())))
        else:
            class_rates.append((room_digits[k], 0.0, int(mask.sum())))

    print(f"\n  [Diagnostics @ epoch {epoch}]")
    print(f"  R(Z) total = {R_total:.2f}")
    for digit, rate, count in class_rates:
        print(f"    R(Z_{digit}) = {rate:.2f}  (n={count})")
    R_compress = sum(r * n / len(Z) for _, r, n in class_rates)
    print(f"  R_compress = {R_compress:.2f},  delta_R = {R_total - R_compress:.2f}")
    off_diag = ortho[~np.eye(n_cls, dtype=bool)].mean()
    print(f"  Ortho: diag_mean={np.diag(ortho).mean():.3f}, off_diag_mean={off_diag:.3f}")

    # Embedding statistics (SIGReg diagnostic)
    Z_norms = np.linalg.norm(Z, axis=1)
    print(f"  Embedding norms: mean={Z_norms.mean():.3f}, std={Z_norms.std():.3f}")

    # UMAP + heatmap
    reducer = umap.UMAP(metric="cosine", n_neighbors=15)
    emb_2d = reducer.fit_transform(Z)

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    axes[0].scatter(emb_2d[:, 0], emb_2d[:, 1], c=labels, cmap="tab10", s=8, alpha=0.5)
    for k in range(n_cls):
        mask = labels == k
        if mask.sum() > 0:
            cx, cy = emb_2d[mask].mean(axis=0)
            axes[0].annotate(str(room_digits[k]), (cx, cy),
                            fontsize=14, fontweight="bold", ha="center",
                            color="black",
                            bbox=dict(boxstyle="round,pad=0.2", fc="white", alpha=0.8))
    axes[0].set_title(f"UMAP of Z (epoch {epoch}) — labels NOT used in training")
    axes[0].set_xticks([])
    axes[0].set_yticks([])

    im = axes[1].imshow(ortho, cmap="RdBu_r", vmin=-1, vmax=1)
    axes[1].set_xticks(range(n_cls))
    axes[1].set_xticklabels(room_digits)
    axes[1].set_yticks(range(n_cls))
    axes[1].set_yticklabels(room_digits)
    axes[1].set_title(f"Room Cosine Similarity (epoch {epoch})")
    fig.colorbar(im, ax=axes[1], shrink=0.8)

    plt.tight_layout()
    fig.savefig(TRAIN_DIR / f"epoch_{epoch}.png", dpi=150, bbox_inches="tight")
    plt.close(fig)

    encoder.train()
    return ortho, R_total


@torch.no_grad()
def evaluate_discrimination(encoder, data):
    """Compute discrimination ratio for fate-A perturbation.
    Uses cosine distance since embeddings are not L2-normalized.
    """
    encoder.eval()

    room_embeddings = {}
    for label_idx, digit in enumerate(data["room_digits"]):
        mask = data["class_labels"] == label_idx
        cells = torch.from_numpy(data["homeostatic"][mask]).float().to(DEVICE)
        if len(cells) == 0:
            continue
        embs = []
        for i in range(0, len(cells), 256):
            embs.append(encoder(cells[i:i+256]))
        room_embeddings[digit] = torch.cat(embs, dim=0).mean(dim=0)

    fate_A_cells = None
    for cells, labels, name in data["perturbed"]:
        if "fate_A" in name and "s1.0" in name:
            fate_A_cells = torch.from_numpy(cells).float().to(DEVICE)
            break

    if fate_A_cells is None or 4 not in room_embeddings or 1 not in room_embeddings:
        print("  Could not evaluate: missing data")
        encoder.train()
        return 0.0

    embs = []
    for i in range(0, min(len(fate_A_cells), 256), 128):
        embs.append(encoder(fate_A_cells[i:i+128]))
    z_pert = torch.cat(embs, dim=0).mean(dim=0)

    # Use cosine distance (embeddings not normalized)
    cos_correct = F.cosine_similarity(z_pert.unsqueeze(0), room_embeddings[4].unsqueeze(0)).item()
    cos_wrong = F.cosine_similarity(z_pert.unsqueeze(0), room_embeddings[1].unsqueeze(0)).item()
    # Also L2 distance for comparison
    dist_correct = (z_pert - room_embeddings[4]).norm().item()
    dist_wrong = (z_pert - room_embeddings[1]).norm().item()
    ratio = dist_wrong / (dist_correct + 1e-8)

    print(f"  DR(L2) = {ratio:.2f}x  (d4={dist_correct:.4f}, d1={dist_wrong:.4f})")
    print(f"  DR(cos) correct_sim={cos_correct:.4f}, wrong_sim={cos_wrong:.4f}")
    if ratio > 2.0:
        print("  PASSED: Linearization Trap avoided")
    elif ratio > 1.0:
        print("  PARTIAL: Correct direction, not strongly discriminated")
    else:
        print("  FAILED: Cannot discriminate fate outcomes")

    encoder.train()
    return ratio


# %% [7] Load data and build models

data = load_proxy_dataset(CONFIG["data_dir"])
n_classes = len(data["room_digits"])
gene_dim = data["homeostatic"].shape[1]

dataset = CellDataset(data["homeostatic"], data["class_labels"])
loader = DataLoader(dataset, batch_size=CONFIG["batch_size"],
                    shuffle=True, num_workers=0, pin_memory=False)

encoder = MLPEncoder(gene_dim, CONFIG["embed_dim"], CONFIG["hidden_dim"]).to(DEVICE)
predictor = JEPAPredictor(CONFIG["embed_dim"], CONFIG["predictor_hidden"]).to(DEVICE)

all_params = list(encoder.parameters()) + list(predictor.parameters())
n_params = sum(p.numel() for p in all_params if p.requires_grad)
print(f"Model: {n_params:,} params, embed_dim={CONFIG['embed_dim']}")

optimizer = torch.optim.AdamW(all_params, lr=CONFIG["lr"],
                               weight_decay=CONFIG["weight_decay"])
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer, T_max=CONFIG["epochs"]
)

# %% [8] Training — Homeostatic cells only, JEPA + SIGReg

METRICS_LOG.write_text("")

print(f"\nTraining for {CONFIG['epochs']} epochs "
      f"(sigreg_weight={CONFIG['sigreg_weight']}, "
      f"context_ratio={CONFIG['context_ratio']}, "
      f"n_projections={CONFIG['sigreg_projs']})\n")

total_time = 0.0
for epoch in range(1, CONFIG["epochs"] + 1):
    encoder.train()
    predictor.train()

    ep_pred, ep_sig, ep_total = 0.0, 0.0, 0.0
    n_batches = 0
    t0 = time.perf_counter()

    for x_batch, y_batch in loader:
        x_batch = x_batch.to(DEVICE)
        # y_batch NOT used for training — only for diagnostics

        x_ctx, x_tgt = gene_set_mask(x_batch, CONFIG["context_ratio"])

        z_ctx = encoder(x_ctx)
        with torch.no_grad():
            z_tgt = encoder(x_tgt)  # stop-gradient on target

        z_pred = predictor(z_ctx)

        pred_loss = F.mse_loss(z_pred, z_tgt.detach())
        sig_loss = sigreg_loss(z_ctx, n_projections=CONFIG["sigreg_projs"])
        loss = pred_loss + CONFIG["sigreg_weight"] * sig_loss

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(all_params, max_norm=1.0)
        optimizer.step()

        ep_pred += pred_loss.item()
        ep_sig += sig_loss.item()
        ep_total += loss.item()
        n_batches += 1

    elapsed = time.perf_counter() - t0
    total_time += elapsed
    scheduler.step()
    avg_pred = ep_pred / n_batches
    avg_sig = ep_sig / n_batches
    avg_total = ep_total / n_batches
    lr_now = scheduler.get_last_lr()[0]

    print(f"Epoch {epoch:3d}/{CONFIG['epochs']} | "
          f"pred={avg_pred:.4f} | sigreg={avg_sig:.6f} | "
          f"total={avg_total:.4f} | lr={lr_now:.2e} | {elapsed:.1f}s")
    log_metrics(epoch=epoch, pred_loss=avg_pred, sigreg_loss=avg_sig,
                total_loss=avg_total, lr=lr_now, time_s=elapsed)

    if epoch % CONFIG["diag_every"] == 0 or epoch == 1 or epoch == CONFIG["epochs"]:
        compute_diagnostics(encoder, data, epoch)
        dr = evaluate_discrimination(encoder, data)
        log_metrics(event="eval", epoch=epoch, DR=dr)

# %% [9] Final Summary

print("\n" + "=" * 60)
print(f"Training complete. Total: {total_time:.1f}s "
      f"({total_time/CONFIG['epochs']:.1f}s/epoch)")
print("=" * 60)

dr = evaluate_discrimination(encoder, data)
log_metrics(event="final", DR=dr, total_time=total_time)

# Save checkpoint
ckpt_path = TRAIN_DIR / "checkpoint.pt"
torch.save({
    "encoder": encoder.state_dict(),
    "predictor": predictor.state_dict(),
    "total_time": total_time,
    "config": CONFIG,
}, ckpt_path)
print(f"Saved checkpoint to {ckpt_path}")


# %% [10] Perturbation Dataset for Phase 2

class PerturbationDataset(Dataset):
    """Each sample: (source_cell, perturbed_cell, pert_type, dose)."""
    def __init__(self, source_cells, perturbed_cells, pert_ids, strengths):
        self.source = torch.from_numpy(source_cells).float()
        self.perturbed = torch.from_numpy(perturbed_cells).float()
        self.pert_ids = torch.from_numpy(pert_ids).long()
        self.strengths = torch.from_numpy(strengths).float()

    def __len__(self):
        return len(self.source)

    def __getitem__(self, idx):
        return self.source[idx], self.perturbed[idx], self.pert_ids[idx], self.strengths[idx]


def build_perturbation_training_data(data):
    """Build paired (source_cell, perturbed_cell) from proxy dataset.

    Skips pert 3 (partial priming) — no single destination.
    Pairs each perturbed cell with a random homeostatic cell from its source room.
    """
    pert_cells = data["pert_cells"]
    pert_labels = data["pert_labels"]
    pert_ids = data["pert_ids"]
    pert_str = data["pert_strengths"]

    use_mask = np.isin(pert_ids, [0, 1, 2, 4])
    pert_cells = pert_cells[use_mask]
    pert_labels = pert_labels[use_mask]
    pert_ids = pert_ids[use_mask]
    pert_str = pert_str[use_mask]

    homeostatic = data["homeostatic"]
    class_labels = data["class_labels"]
    rng = np.random.default_rng(42)
    source_cells = np.zeros_like(pert_cells)
    for src_label in np.unique(pert_labels):
        mask = pert_labels == src_label
        room_cells = homeostatic[class_labels == src_label]
        chosen = rng.integers(0, len(room_cells), size=mask.sum())
        source_cells[mask] = room_cells[chosen]

    print(f"Phase 2 data: {len(pert_cells)} perturbation pairs "
          f"(pert types: {sorted(set(pert_ids))})")
    return PerturbationDataset(source_cells, pert_cells, pert_ids, pert_str)


# %% [11] Phase 2 — Perturbation Prediction (World Model)
#
# Key differences from geo_jepa_simple.py Phase B:
#   1. AdaLN-conditioned transformer predictor (not MLP concatenation)
#   2. Encoder trained jointly (not frozen) — SIGReg prevents collapse
#   3. MSE loss in R^d (not cosine on unit sphere)

print("\n" + "=" * 60)
print("Phase 2: Perturbation Prediction (World Model)")
print("=" * 60)

pert_dataset = build_perturbation_training_data(data)
pert_loader = DataLoader(pert_dataset, batch_size=CONFIG["batch_size"],
                         shuffle=True, num_workers=0, pin_memory=False)

pert_predictor = PerturbationPredictor(
    CONFIG["embed_dim"],
    n_pert_types=CONFIG["n_pert_types"],
    pert_embed_dim=CONFIG["pert_embed_dim"],
    n_layers=CONFIG["adaln_layers"],
    n_heads=CONFIG["adaln_heads"],
).to(DEVICE)

n_pert_params = sum(p.numel() for p in pert_predictor.parameters())
print(f"PerturbationPredictor: {n_pert_params:,} params "
      f"({CONFIG['adaln_layers']} AdaLN layers, {CONFIG['adaln_heads']} heads)")

# Joint training: encoder (low LR) + predictor (normal LR)
phase2_optimizer = torch.optim.AdamW([
    {"params": encoder.parameters(), "lr": CONFIG["phase2_encoder_lr"]},
    {"params": pert_predictor.parameters(), "lr": CONFIG["phase2_lr"]},
], weight_decay=CONFIG["weight_decay"])
phase2_scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    phase2_optimizer, T_max=CONFIG["phase2_epochs"]
)

phase2_time = 0.0
for epoch in range(1, CONFIG["phase2_epochs"] + 1):
    encoder.train()
    pert_predictor.train()
    ep_pred, ep_sig, ep_total = 0.0, 0.0, 0.0
    n_batches = 0
    t0 = time.perf_counter()

    for src_cells, pert_cells_batch, pert_ids_batch, doses in pert_loader:
        src_cells = src_cells.to(DEVICE)
        pert_cells_batch = pert_cells_batch.to(DEVICE)
        pert_ids_batch = pert_ids_batch.to(DEVICE)
        doses = doses.to(DEVICE)

        z_src = encoder(src_cells)
        with torch.no_grad():
            z_dest_target = encoder(pert_cells_batch)  # stop-gradient on target

        z_dest_pred = pert_predictor(z_src, pert_ids_batch, doses)

        pred_loss = F.mse_loss(z_dest_pred, z_dest_target.detach())
        sig_loss = sigreg_loss(z_src, n_projections=CONFIG["sigreg_projs"])
        loss = pred_loss + CONFIG["sigreg_weight"] * sig_loss

        phase2_optimizer.zero_grad()
        loss.backward()
        all_p2_params = list(encoder.parameters()) + list(pert_predictor.parameters())
        torch.nn.utils.clip_grad_norm_(all_p2_params, max_norm=1.0)
        phase2_optimizer.step()

        ep_pred += pred_loss.item()
        ep_sig += sig_loss.item()
        ep_total += loss.item()
        n_batches += 1

    elapsed = time.perf_counter() - t0
    phase2_time += elapsed
    phase2_scheduler.step()
    avg_pred = ep_pred / n_batches
    avg_sig = ep_sig / n_batches
    avg_total = ep_total / n_batches
    lr_now = phase2_scheduler.get_last_lr()[0]

    print(f"Phase 2 Epoch {epoch:3d}/{CONFIG['phase2_epochs']} | "
          f"pred={avg_pred:.4f} | sigreg={avg_sig:.6f} | "
          f"total={avg_total:.4f} | lr={lr_now:.2e} | {elapsed:.1f}s")
    log_metrics(phase="2", epoch=epoch, pred_loss=avg_pred,
                sigreg_loss=avg_sig, total_loss=avg_total,
                lr=lr_now, time_s=elapsed)


# %% [12] Trajectory Evaluation

@torch.no_grad()
def evaluate_trajectories(encoder, pert_pred, data):
    """Evaluate trajectory prediction: DR per perturbation type + UMAP."""
    encoder.eval()
    pert_pred.eval()
    room_digits = data["room_digits"]

    # Compute room centroids
    room_centroids = {}
    cells_t = torch.from_numpy(data["homeostatic"]).float().to(DEVICE)
    labels = data["class_labels"]
    all_z = []
    for i in range(0, len(cells_t), 256):
        all_z.append(encoder(cells_t[i:i+256]))
    Z_home = torch.cat(all_z, dim=0)

    for label_idx, digit in enumerate(room_digits):
        mask = labels == label_idx
        if mask.sum() > 0:
            room_centroids[digit] = Z_home[mask].mean(dim=0)

    fate_dests = {int(k): v for k, v in data["fate_destinations"].items() if v is not None}

    pert_cells = data["pert_cells"]
    pert_labels = data["pert_labels"]
    pert_ids_np = data["pert_ids"]
    pert_str = data["pert_strengths"]

    umap_z, umap_colors = [], []
    sub_idx = np.random.choice(len(Z_home), min(2000, len(Z_home)), replace=False)
    umap_z.append(Z_home[sub_idx].cpu().numpy())
    umap_colors.extend(["homeostatic"] * len(sub_idx))

    print("\n  [Trajectory Evaluation]")
    for pid in sorted(fate_dests.keys()):
        target_digit = fate_dests[pid]
        wrong_digits = [d for d in [1, 4] if d != target_digit]
        if not wrong_digits:
            continue
        wrong_digit = wrong_digits[0]

        if target_digit not in room_centroids or wrong_digit not in room_centroids:
            continue

        mask = (pert_ids_np == pid) & (pert_str == 1.0)
        if mask.sum() == 0:
            continue

        src_label = pert_labels[mask][0]
        src_room_cells = data["homeostatic"][data["class_labels"] == src_label]
        rng = np.random.default_rng(123)
        n_pred = int(mask.sum())
        chosen = rng.integers(0, len(src_room_cells), size=n_pred)
        src_cells_batch = torch.from_numpy(src_room_cells[chosen]).float().to(DEVICE)
        pert_id_batch = torch.full((n_pred,), pid, dtype=torch.long, device=DEVICE)
        dose_batch = torch.ones(n_pred, device=DEVICE)

        z_src = encoder(src_cells_batch)
        z_pred = pert_pred(z_src, pert_id_batch, dose_batch)
        z_pred_mean = z_pred.mean(dim=0)

        actual_pert = torch.from_numpy(pert_cells[mask]).float().to(DEVICE)
        z_actual = []
        for i in range(0, len(actual_pert), 256):
            z_actual.append(encoder(actual_pert[i:i+256]))
        z_actual = torch.cat(z_actual, dim=0)
        z_actual_mean = z_actual.mean(dim=0)

        d_correct = (z_pred_mean - room_centroids[target_digit]).norm().item()
        d_wrong = (z_pred_mean - room_centroids[wrong_digit]).norm().item()
        dr_pred = d_wrong / (d_correct + 1e-8)

        d_correct_a = (z_actual_mean - room_centroids[target_digit]).norm().item()
        d_wrong_a = (z_actual_mean - room_centroids[wrong_digit]).norm().item()
        dr_actual = d_wrong_a / (d_correct_a + 1e-8)

        pert_name = {0: "Fate-A->4", 1: "Fate-B->1", 2: "InRoom->4", 4: "Combo->4"}.get(pid, f"pert{pid}")
        status = "PASS" if dr_pred > 2.0 else ("PARTIAL" if dr_pred > 1.0 else "FAIL")
        print(f"  [{status}] {pert_name}: predicted DR={dr_pred:.2f}x  "
              f"(actual DR={dr_actual:.2f}x)")
        log_metrics(phase="2", event="trajectory", pert=pert_name,
                    predicted_DR=dr_pred, actual_DR=dr_actual)

        umap_z.append(z_actual.cpu().numpy())
        umap_colors.extend([f"actual_p{pid}"] * len(z_actual))
        umap_z.append(z_pred.cpu().numpy())
        umap_colors.extend([f"pred_p{pid}"] * len(z_pred))

    # UMAP visualization
    Z_all = np.vstack(umap_z)
    reducer = umap.UMAP(metric="cosine", n_neighbors=15)
    emb_2d = reducer.fit_transform(Z_all)

    fig, ax = plt.subplots(1, 1, figsize=(10, 8))
    color_map = {
        "homeostatic": "#cccccc",
        "actual_p0": "#1f77b4", "pred_p0": "#aec7e8",
        "actual_p1": "#ff7f0e", "pred_p1": "#ffbb78",
        "actual_p2": "#2ca02c", "pred_p2": "#98df8a",
        "actual_p4": "#d62728", "pred_p4": "#ff9896",
    }
    for label in ["homeostatic", "actual_p0", "pred_p0", "actual_p1", "pred_p1",
                   "actual_p2", "pred_p2", "actual_p4", "pred_p4"]:
        mask = np.array([c == label for c in umap_colors])
        if mask.sum() == 0:
            continue
        alpha = 0.2 if label == "homeostatic" else 0.6
        size = 4 if label == "homeostatic" else 12
        marker = "o" if "actual" in label or label == "homeostatic" else "x"
        display = label.replace("actual_p", "actual pert ").replace("pred_p", "predicted pert ")
        ax.scatter(emb_2d[mask, 0], emb_2d[mask, 1],
                   c=color_map.get(label, "gray"), s=size, alpha=alpha,
                   marker=marker, label=display)

    ax.legend(loc="upper right", fontsize=8, markerscale=2)
    ax.set_title("Phase 2: Predicted vs Actual Perturbation Trajectories")
    ax.set_xticks([])
    ax.set_yticks([])
    plt.tight_layout()
    fig.savefig(TRAIN_DIR / "phase2_trajectories.png", dpi=150, bbox_inches="tight")
    plt.close(fig)


evaluate_trajectories(encoder, pert_predictor, data)

# %% [13] Final Summary

print("\n" + "=" * 60)
print(f"Phase 1: {total_time:.1f}s  |  Phase 2: {phase2_time:.1f}s  |  "
      f"Total: {total_time + phase2_time:.1f}s")
print("=" * 60)
evaluate_discrimination(encoder, data)

# Save Phase 2 checkpoint
ckpt_path = TRAIN_DIR / "checkpoint_phase2.pt"
torch.save({
    "encoder": encoder.state_dict(),
    "jepa_predictor": predictor.state_dict(),
    "pert_predictor": pert_predictor.state_dict(),
    "phase1_time": total_time,
    "phase2_time": phase2_time,
    "config": CONFIG,
}, ckpt_path)
print(f"Saved Phase 2 checkpoint to {ckpt_path}")
