"""
Geo-JEPA Simple: MLP Encoder + MCR² Loss + JEPA Training
==========================================================
Two-phase training on MNIST proxy dataset simulating scRNA-seq.

Phase A — Room Separation (homeostatic cells):
  MLP encoder (2000D → 512 → 512 → 128, L2-normalized) learns orthogonal
  subspaces per cell type via MCR² loss (d×d eigvalsh, MPS-native).
  JEPA gene-set masking + EMA target encoder for self-supervised structure.
  Result: DR ~1.9-2.3x, off-diagonal cosine ~0.02, clean UMAP separation.

Phase B — Trajectory Prediction (perturbation cells):
  Frozen encoder + TrajectoryPredictor MLP learns to map
  (z_source + perturbation_embedding) → z_destination via residual displacement.
  Cosine similarity loss on the unit sphere.
  Result: Predicted DR ~1.25-1.37x (actual DR ~1.9-2.3x). Predictions land in
  the correct neighborhood but lack precision — likely needs encoder fine-tuning
  or richer perturbation representations. See GEO_JEPA_PLAN.md for next steps.

Output: results/training/ (metrics.jsonl, PNGs, Phase A checkpoint)
Dataset: MNIST proxy (generated by build_proxy_dataset.py)
"""

# %% [1] Imports & Setup
import json
import time
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
import umap
from pathlib import Path
from torch.utils.data import Dataset, DataLoader
from copy import deepcopy

DEVICE = torch.device(
    "mps" if torch.backends.mps.is_available()
    else "cuda" if torch.cuda.is_available()
    else "cpu"
)
print(f"Using device: {DEVICE}")

# %% [2] Configuration
CONFIG = {
    "data_dir":         "./data",
    "embed_dim":        128,
    "hidden_dim":       512,
    "predictor_hidden": 256,
    "context_ratio":    0.75,
    "ema_momentum":     0.996,
    "mcr_weight":       1.0,       # MCR² weight — start high to force separation
    "eps":              0.5,
    "batch_size":       512,       # larger batches help MCR² see class structure
    "epochs":           40,
    "lr":               1e-3,
    "weight_decay":     1e-4,
    "diag_every":       10,
    # Phase B: trajectory prediction
    "phase_b_epochs":   40,
    "phase_b_lr":       1e-3,
    "pert_embed_dim":   32,
}

# %% [2b] Training Output Directory
TRAIN_DIR = Path("results/training")
TRAIN_DIR.mkdir(parents=True, exist_ok=True)
METRICS_LOG = TRAIN_DIR / "metrics.jsonl"
print(f"Training output: {TRAIN_DIR}")


def log_metrics(**kwargs):
    """Append one JSON line to metrics log. Tail-friendly, append-only."""
    with open(METRICS_LOG, "a") as f:
        f.write(json.dumps(kwargs) + "\n")


# %% [3] Dataset
def load_proxy_dataset(data_dir: str = "./data"):
    """Load pre-built proxy dataset from .npz file."""
    npz_path = Path(data_dir) / "proxy_dataset.npz"
    meta_path = Path(data_dir) / "proxy_dataset_metadata.json"

    if not npz_path.exists():
        raise FileNotFoundError(
            f"Dataset not found at {npz_path}. "
            "Run first: python build_proxy_dataset.py"
        )

    data = np.load(npz_path)
    with open(meta_path) as f:
        meta = json.load(f)

    pert_cells = data["perturbation_cells"]
    pert_ids = data["perturbation_ids"]
    pert_strengths = data["perturbation_strengths"]
    pert_labels = data["perturbation_labels"]  # source room label
    pert_names = meta["perturbation_names"]

    perturbed = []
    for pid in sorted(set(pert_ids)):
        for strength in sorted(set(pert_strengths[pert_ids == pid])):
            mask = (pert_ids == pid) & (pert_strengths == strength)
            cells = pert_cells[mask]
            name = f"{pert_names[str(pid)]}_s{strength}"
            labels = np.full(len(cells), pid, dtype=int)
            perturbed.append((cells, labels, name))

    homeostatic = data["homeostatic_cells"]
    gene_dim = homeostatic.shape[1]
    print(f"Dataset loaded: {homeostatic.shape[0]} homeostatic, "
          f"{gene_dim}D, ~{100*(homeostatic==0).mean():.0f}% zeros")

    return {
        "homeostatic": homeostatic,
        "class_labels": data["homeostatic_labels"],
        "perturbed": perturbed,
        "pert_cells": pert_cells,
        "pert_ids": pert_ids,
        "pert_strengths": pert_strengths,
        "pert_labels": pert_labels,
        "ood_test": (data["ood_cells"], data["ood_labels"], "ood_toward_7"),
        "room_digits": meta["room_digits"],
        "fate_destinations": meta.get("fate_destinations", {}),
    }


class CellDataset(Dataset):
    def __init__(self, cells: np.ndarray, labels: np.ndarray):
        self.cells = torch.from_numpy(cells).float()
        self.labels = torch.from_numpy(labels).long()

    def __len__(self):
        return len(self.cells)

    def __getitem__(self, idx):
        return self.cells[idx], self.labels[idx]


data = load_proxy_dataset(CONFIG["data_dir"])
n_classes = len(data["room_digits"])
gene_dim = data["homeostatic"].shape[1]

dataset = CellDataset(data["homeostatic"], data["class_labels"])
loader = DataLoader(dataset, batch_size=CONFIG["batch_size"],
                    shuffle=True, num_workers=0, pin_memory=False)


# %% [3b] Perturbation Dataset for Phase B
class PerturbationDataset(Dataset):
    """Each sample: (source_cell, perturbed_cell, pert_type, dose)."""
    def __init__(self, source_cells, perturbed_cells, pert_ids, strengths):
        self.source = torch.from_numpy(source_cells).float()
        self.perturbed = torch.from_numpy(perturbed_cells).float()
        self.pert_ids = torch.from_numpy(pert_ids).long()
        self.strengths = torch.from_numpy(strengths).float()

    def __len__(self):
        return len(self.source)

    def __getitem__(self, idx):
        return self.source[idx], self.perturbed[idx], self.pert_ids[idx], self.strengths[idx]


def build_perturbation_training_data(data):
    """Build paired (source_cell, perturbed_cell) from already-loaded data.

    Uses data["pert_*"] arrays from load_proxy_dataset().
    Skips pert 3 (partial priming) — no single destination.
    Pairs each perturbed cell with a random homeostatic cell from its source room.
    """
    pert_cells = data["pert_cells"]
    pert_labels = data["pert_labels"]  # source room label per cell
    pert_ids = data["pert_ids"]
    pert_str = data["pert_strengths"]

    # Only use perturbations with deterministic destinations (skip pert 3)
    use_mask = np.isin(pert_ids, [0, 1, 2, 4])
    pert_cells = pert_cells[use_mask]
    pert_labels = pert_labels[use_mask]
    pert_ids = pert_ids[use_mask]
    pert_str = pert_str[use_mask]

    # For each perturbed cell, sample a random source cell from its source room
    homeostatic = data["homeostatic"]
    class_labels = data["class_labels"]
    rng = np.random.default_rng(42)
    source_cells = np.zeros_like(pert_cells)
    for src_label in np.unique(pert_labels):
        mask = pert_labels == src_label
        room_cells = homeostatic[class_labels == src_label]
        chosen = rng.integers(0, len(room_cells), size=mask.sum())
        source_cells[mask] = room_cells[chosen]

    print(f"Phase B data: {len(pert_cells)} perturbation pairs "
          f"(pert types: {sorted(set(pert_ids))})")
    return PerturbationDataset(source_cells, pert_cells, pert_ids, pert_str)

# %% [4] MCR² Loss (d×d formulation — stable on MPS, no Cholesky)
def coding_rate(Z: torch.Tensor, eps: float = 0.5) -> torch.Tensor:
    """
    R(Z, eps) = (d/2) log det(I + d/(n*eps^2) Z^T Z)
    Uses eigvalsh on (d×d) matrix — works on MPS without fallback.
    """
    n, d = Z.shape
    alpha = d / (n * eps ** 2)
    M = torch.eye(d, device=Z.device) + alpha * (Z.T @ Z)
    if M.device.type == "mps":
        eigvals = torch.linalg.eigvalsh(M.cpu()).to(Z.device)
    else:
        eigvals = torch.linalg.eigvalsh(M)
    return 0.5 * torch.sum(torch.log(eigvals.clamp(min=1e-7)))


def mcr2_loss(Z, labels, n_classes, eps=0.5):
    """MCR² with hard labels. Returns (loss, R_total, R_compress, delta_R)."""
    R_total = coding_rate(Z, eps)
    R_compress = torch.tensor(0.0, device=Z.device)
    n = Z.shape[0]
    for k in range(n_classes):
        mask = labels == k
        n_k = mask.sum()
        if n_k < 2:
            continue
        R_compress = R_compress + (n_k / n) * coding_rate(Z[mask], eps)

    delta_R = R_total - R_compress
    return -delta_R, R_total.item(), R_compress.item(), delta_R.item()

# %% [5] Models
class MLPEncoder(nn.Module):
    """MLP encoder: gene_dim -> hidden -> embed_dim, L2 normalized.
    Placeholder for future attention + ReduNet."""
    def __init__(self, gene_dim, embed_dim, hidden_dim=512):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(gene_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, embed_dim),
        )

    def forward(self, x):
        return F.normalize(self.net(x), dim=1)


class Predictor(nn.Module):
    """MLP predictor: z_context -> z_target_hat."""
    def __init__(self, embed_dim, hidden_dim=256):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(embed_dim, hidden_dim),
            nn.GELU(),
            nn.LayerNorm(hidden_dim),
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, embed_dim),
        )

    def forward(self, z):
        return F.normalize(self.net(z), dim=1)


class TrajectoryPredictor(nn.Module):
    """Predicts destination via residual displacement from source embedding.

    Instead of predicting absolute z_dest, predicts a delta:
        z_dest = normalize(z_source + delta(z_source, pert, dose))

    This gives the predictor a strong prior: "start where you are, shift
    toward the destination." The MLP only needs to learn the displacement,
    which is much easier than learning absolute positions.
    """
    def __init__(self, embed_dim, n_pert_types=5, pert_embed_dim=32, hidden_dim=256):
        super().__init__()
        self.pert_embed = nn.Embedding(n_pert_types, pert_embed_dim)
        self.net = nn.Sequential(
            nn.Linear(embed_dim + pert_embed_dim, hidden_dim),
            nn.GELU(),
            nn.LayerNorm(hidden_dim),
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, embed_dim),
        )

    def forward(self, z_source, pert_id, dose):
        """
        z_source: (B, embed_dim) — encoded source cell
        pert_id:  (B,) int — perturbation type (0-4)
        dose:     (B,) float — strength 0.3/0.6/1.0
        """
        pe = self.pert_embed(pert_id) * dose.unsqueeze(1)
        h = torch.cat([z_source, pe], dim=1)
        delta = self.net(h)
        return F.normalize(z_source + delta, dim=1)


def gene_set_mask(x, context_ratio=0.75):
    """Partition genes into context (visible) and target (masked)."""
    gene_dim = x.shape[1]
    n_context = int(gene_dim * context_ratio)
    perm = torch.randperm(gene_dim, device=x.device)
    x_context = torch.zeros_like(x)
    x_context[:, perm[:n_context]] = x[:, perm[:n_context]]
    x_target = torch.zeros_like(x)
    x_target[:, perm[n_context:]] = x[:, perm[n_context:]]
    return x_context, x_target


@torch.no_grad()
def ema_update(online, target, momentum=0.996):
    for p_o, p_t in zip(online.parameters(), target.parameters()):
        p_t.data.mul_(momentum).add_(p_o.data, alpha=1.0 - momentum)


# Build models
encoder_online = MLPEncoder(gene_dim, CONFIG["embed_dim"], CONFIG["hidden_dim"]).to(DEVICE)
encoder_target = deepcopy(encoder_online).to(DEVICE)
for p in encoder_target.parameters():
    p.requires_grad_(False)
predictor = Predictor(CONFIG["embed_dim"], CONFIG["predictor_hidden"]).to(DEVICE)

params = list(encoder_online.parameters()) + list(predictor.parameters())
n_params = sum(p.numel() for p in params if p.requires_grad)
print(f"Model: {n_params:,} params, embed_dim={CONFIG['embed_dim']}")

params = list(encoder_online.parameters()) + list(predictor.parameters())
optimizer = torch.optim.AdamW(params, lr=CONFIG["lr"],
                              weight_decay=CONFIG["weight_decay"])
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer, T_max=CONFIG["epochs"]
)

# %% [6] Diagnostics
@torch.no_grad()
def compute_diagnostics(encoder, data, epoch):
    """Compute and display diagnostic plots: UMAP + orthogonality heatmap."""
    encoder.eval()

    # Embed all homeostatic cells
    cells = torch.from_numpy(data["homeostatic"]).float().to(DEVICE)
    labels = data["class_labels"]
    room_digits = data["room_digits"]
    all_z = []
    for i in range(0, len(cells), 256):
        all_z.append(encoder(cells[i:i+256]).cpu())
    Z = torch.cat(all_z, dim=0).numpy()
    n_cls = len(room_digits)

    # Orthogonality matrix (cosine similarity between room centroids)
    centroids = np.zeros((n_cls, Z.shape[1]))
    for k in range(n_cls):
        mask = labels == k
        if mask.sum() > 0:
            centroids[k] = Z[mask].mean(axis=0)
    norms = np.linalg.norm(centroids, axis=1, keepdims=True) + 1e-8
    centroids_norm = centroids / norms
    ortho = centroids_norm @ centroids_norm.T

    # Per-class coding rates
    Z_tensor = torch.from_numpy(Z).float()
    R_total = coding_rate(Z_tensor, eps=0.5).item()
    class_rates = []
    for k in range(n_cls):
        mask = labels == k
        if mask.sum() >= 2:
            class_rates.append((room_digits[k], coding_rate(Z_tensor[mask], eps=0.5).item(), int(mask.sum())))
        else:
            class_rates.append((room_digits[k], 0.0, int(mask.sum())))

    # Print summary
    print(f"\n  [Diagnostics @ epoch {epoch}]")
    print(f"  R(Z) total = {R_total:.2f}")
    for digit, rate, count in class_rates:
        print(f"    R(Z_{digit}) = {rate:.2f}  (n={count})")
    R_compress = sum(r * n / len(Z) for _, r, n in class_rates)
    print(f"  R_compress = {R_compress:.2f},  delta_R = {R_total - R_compress:.2f}")
    off_diag = ortho[~np.eye(n_cls, dtype=bool)].mean()
    print(f"  Ortho: diag_mean={np.diag(ortho).mean():.3f}, off_diag_mean={off_diag:.3f}")

    # UMAP + heatmap
    reducer = umap.UMAP(metric="cosine", n_neighbors=15)
    emb_2d = reducer.fit_transform(Z)

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    axes[0].scatter(emb_2d[:, 0], emb_2d[:, 1], c=labels, cmap="tab10", s=8, alpha=0.5)
    for k in range(n_cls):
        mask = labels == k
        if mask.sum() > 0:
            cx, cy = emb_2d[mask].mean(axis=0)
            axes[0].annotate(str(room_digits[k]), (cx, cy),
                            fontsize=14, fontweight="bold", ha="center",
                            color="black",
                            bbox=dict(boxstyle="round,pad=0.2", fc="white", alpha=0.8))
    axes[0].set_title(f"UMAP of Z (epoch {epoch})")
    axes[0].set_xticks([])
    axes[0].set_yticks([])

    im = axes[1].imshow(ortho, cmap="RdBu_r", vmin=-1, vmax=1)
    axes[1].set_xticks(range(n_cls))
    axes[1].set_xticklabels(room_digits)
    axes[1].set_yticks(range(n_cls))
    axes[1].set_yticklabels(room_digits)
    axes[1].set_title(f"Room Cosine Similarity (epoch {epoch})")
    fig.colorbar(im, ax=axes[1], shrink=0.8)

    plt.tight_layout()
    fig.savefig(TRAIN_DIR / f"phase_a_epoch_{epoch}.png", dpi=150, bbox_inches="tight")
    plt.show()

    encoder.train()
    return ortho, R_total


@torch.no_grad()
def evaluate_discrimination(encoder, data):
    """Compute discrimination ratio for fate-A perturbation."""
    encoder.eval()

    room_embeddings = {}
    for label_idx, digit in enumerate(data["room_digits"]):
        mask = data["class_labels"] == label_idx
        cells = torch.from_numpy(data["homeostatic"][mask]).float().to(DEVICE)
        if len(cells) == 0:
            continue
        embs = []
        for i in range(0, len(cells), 256):
            embs.append(encoder(cells[i:i+256]))
        room_embeddings[digit] = torch.cat(embs, dim=0).mean(dim=0)

    fate_A_cells = None
    for cells, labels, name in data["perturbed"]:
        if "fate_A" in name and "s1.0" in name:
            fate_A_cells = torch.from_numpy(cells).float().to(DEVICE)
            break

    if fate_A_cells is None or 4 not in room_embeddings or 1 not in room_embeddings:
        print("  Could not evaluate: missing data")
        encoder.train()
        return 0.0

    embs = []
    for i in range(0, min(len(fate_A_cells), 256), 128):
        embs.append(encoder(fate_A_cells[i:i+128]))
    z_pert = torch.cat(embs, dim=0).mean(dim=0)

    dist_correct = (z_pert - room_embeddings[4]).norm().item()
    dist_wrong = (z_pert - room_embeddings[1]).norm().item()
    ratio = dist_wrong / (dist_correct + 1e-8)

    print(f"  DR = {ratio:.2f}x  (d_correct={dist_correct:.4f}, d_wrong={dist_wrong:.4f})")
    if ratio > 2.0:
        print("  PASSED: Linearization Trap avoided")
    elif ratio > 1.0:
        print("  PARTIAL: Correct direction, not strongly discriminated")
    else:
        print("  FAILED: Cannot discriminate fate outcomes")

    encoder.train()
    return ratio

# %% [7] Phase A — Room Separation (MCR² + JEPA masking)
PHASE_A_CKPT = TRAIN_DIR / "phase_a_checkpoint.pt"

if PHASE_A_CKPT.exists():
    print(f"\nLoading Phase A checkpoint from {PHASE_A_CKPT}")
    ckpt = torch.load(PHASE_A_CKPT, map_location=DEVICE, weights_only=True)
    encoder_online.load_state_dict(ckpt["encoder_online"])
    encoder_target.load_state_dict(ckpt["encoder_target"])
    predictor.load_state_dict(ckpt["predictor"])
    total_time = ckpt["total_time"]
    print(f"Phase A restored (trained {CONFIG['epochs']} epochs in {total_time:.1f}s)")
    METRICS_LOG.write_text("")
    dr = evaluate_discrimination(encoder_online, data)
    log_metrics(phase="a_loaded", total_time=total_time, DR=dr)
else:
    METRICS_LOG.write_text("")
    all_params = list(encoder_online.parameters()) + list(predictor.parameters())

    print(f"\nTraining for {CONFIG['epochs']} epochs "
          f"(mcr_weight={CONFIG['mcr_weight']}, context_ratio={CONFIG['context_ratio']})\n")

    total_time = 0.0
    for epoch in range(1, CONFIG["epochs"] + 1):
        encoder_online.train()
        predictor.train()

        ep_pred, ep_mcr, ep_dr = 0.0, 0.0, 0.0
        n_batches = 0
        t0 = time.perf_counter()

        for x_batch, y_batch in loader:
            x_batch = x_batch.to(DEVICE)
            y_batch = y_batch.to(DEVICE)

            x_ctx, x_tgt = gene_set_mask(x_batch, CONFIG["context_ratio"])

            z_ctx = encoder_online(x_ctx)
            with torch.no_grad():
                z_tgt = encoder_target(x_tgt)

            z_pred = predictor(z_ctx)

            pred_loss = F.mse_loss(z_pred, z_tgt.detach())
            mcr_loss, R_tot, R_comp, dR = mcr2_loss(
                z_ctx, y_batch, n_classes, eps=CONFIG["eps"]
            )
            loss = pred_loss + CONFIG["mcr_weight"] * mcr_loss

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(all_params, max_norm=1.0)
            optimizer.step()
            ema_update(encoder_online, encoder_target, CONFIG["ema_momentum"])

            ep_pred += pred_loss.item()
            ep_mcr += mcr_loss.item()
            ep_dr += dR
            n_batches += 1

        elapsed = time.perf_counter() - t0
        total_time += elapsed
        scheduler.step()
        avg_pred = ep_pred / n_batches
        avg_mcr = ep_mcr / n_batches
        avg_dr = ep_dr / n_batches
        lr_now = scheduler.get_last_lr()[0]

        print(f"Epoch {epoch:3d}/{CONFIG['epochs']} | "
              f"pred={avg_pred:.4f} | mcr={avg_mcr:.2f} | "
              f"dR={avg_dr:.2f} | lr={lr_now:.2e} | {elapsed:.1f}s")
        log_metrics(phase="A", epoch=epoch, pred_loss=avg_pred,
                    mcr_loss=avg_mcr, delta_R=avg_dr, lr=lr_now, time_s=elapsed)

        if epoch % CONFIG["diag_every"] == 0 or epoch == 1 or epoch == CONFIG["epochs"]:
            compute_diagnostics(encoder_online, data, epoch)
            dr = evaluate_discrimination(encoder_online, data)
            log_metrics(phase="A", event="eval", epoch=epoch, DR=dr)

    # Save checkpoint
    print(f"\nSaving Phase A checkpoint to {PHASE_A_CKPT}")
    torch.save({
        "encoder_online": encoder_online.state_dict(),
        "encoder_target": encoder_target.state_dict(),
        "predictor": predictor.state_dict(),
        "total_time": total_time,
        "config": CONFIG,
    }, PHASE_A_CKPT)

    print("\n" + "=" * 60)
    print(f"Phase A complete. Total: {total_time:.1f}s ({total_time/CONFIG['epochs']:.1f}s/epoch)")
    print("=" * 60)
    evaluate_discrimination(encoder_online, data)

# %% [8] Phase B — Trajectory Prediction
# Freeze encoder, train TrajectoryPredictor to map (z_source, pert) -> z_destination

# Clear Phase B artifacts from previous runs
for f in TRAIN_DIR.glob("phase_b_*"):
    f.unlink()
if METRICS_LOG.exists():
    lines = [line for line in METRICS_LOG.read_text().splitlines()
             if '"phase": "A"' in line or '"phase": "a_loaded"' in line]
    METRICS_LOG.write_text("\n".join(lines) + "\n" if lines else "")

print("\n" + "=" * 60)
print("Phase B: Trajectory Prediction")
print("=" * 60)

# Build perturbation dataset
pert_dataset = build_perturbation_training_data(data)
pert_loader = DataLoader(pert_dataset, batch_size=CONFIG["batch_size"],
                         shuffle=True, num_workers=0, pin_memory=False)

# Build trajectory predictor
traj_predictor = TrajectoryPredictor(
    CONFIG["embed_dim"], n_pert_types=5,
    pert_embed_dim=CONFIG["pert_embed_dim"],
    hidden_dim=CONFIG["predictor_hidden"],
).to(DEVICE)

n_traj_params = sum(p.numel() for p in traj_predictor.parameters())
print(f"TrajectoryPredictor: {n_traj_params:,} params")

# Freeze encoder — room structure is learned, now learn trajectories on top
encoder_online.eval()
for p in encoder_online.parameters():
    p.requires_grad_(False)

traj_optimizer = torch.optim.AdamW(
    traj_predictor.parameters(),
    lr=CONFIG["phase_b_lr"], weight_decay=CONFIG["weight_decay"]
)
traj_scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    traj_optimizer, T_max=CONFIG["phase_b_epochs"]
)

phase_b_time = 0.0
for epoch in range(1, CONFIG["phase_b_epochs"] + 1):
    traj_predictor.train()
    ep_loss = 0.0
    n_batches = 0
    t0 = time.perf_counter()

    for src_cells, pert_cells, pert_ids, doses in pert_loader:
        src_cells = src_cells.to(DEVICE)
        pert_cells = pert_cells.to(DEVICE)
        pert_ids = pert_ids.to(DEVICE)
        doses = doses.to(DEVICE)

        with torch.no_grad():
            z_src = encoder_online(src_cells)
            z_dest_target = encoder_online(pert_cells)

        z_dest_pred = traj_predictor(z_src, pert_ids, doses)

        loss = 1.0 - F.cosine_similarity(z_dest_pred, z_dest_target.detach(), dim=1).mean()

        traj_optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(traj_predictor.parameters(), max_norm=1.0)
        traj_optimizer.step()

        ep_loss += loss.item()
        n_batches += 1

    elapsed = time.perf_counter() - t0
    phase_b_time += elapsed
    traj_scheduler.step()
    avg_loss = ep_loss / n_batches
    lr_now = traj_scheduler.get_last_lr()[0]

    print(f"Phase B Epoch {epoch:3d}/{CONFIG['phase_b_epochs']} | "
          f"traj_loss={avg_loss:.6f} | lr={lr_now:.2e} | {elapsed:.1f}s")
    log_metrics(phase="B", epoch=epoch, traj_loss=avg_loss, lr=lr_now, time_s=elapsed)

# %% [9] Trajectory Diagnostics
@torch.no_grad()
def evaluate_trajectories(encoder, traj_pred, data):
    """Evaluate trajectory prediction: DR per perturbation type + UMAP."""
    encoder.eval()
    traj_pred.eval()
    room_digits = data["room_digits"]

    # Compute room centroids
    room_centroids = {}
    cells_t = torch.from_numpy(data["homeostatic"]).float().to(DEVICE)
    labels = data["class_labels"]
    all_z = []
    for i in range(0, len(cells_t), 256):
        all_z.append(encoder(cells_t[i:i+256]))
    Z_home = torch.cat(all_z, dim=0)

    for label_idx, digit in enumerate(room_digits):
        mask = labels == label_idx
        if mask.sum() > 0:
            room_centroids[digit] = Z_home[mask].mean(dim=0)

    # Fate destinations: pert_id -> target digit
    fate_dests = {int(k): v for k, v in data["fate_destinations"].items() if v is not None}

    # Perturbation data (already loaded)
    pert_cells = data["pert_cells"]
    pert_labels = data["pert_labels"]
    pert_ids_np = data["pert_ids"]
    pert_str = data["pert_strengths"]

    # For UMAP: collect homeostatic + actual perturbed + predicted embeddings
    umap_z, umap_colors, umap_markers = [], [], []
    # Add homeostatic (subsample for speed)
    sub_idx = np.random.choice(len(Z_home), min(2000, len(Z_home)), replace=False)
    umap_z.append(Z_home[sub_idx].cpu().numpy())
    umap_colors.extend(["homeostatic"] * len(sub_idx))
    umap_markers.extend(["o"] * len(sub_idx))

    print("\n  [Trajectory Evaluation]")
    for pid in sorted(fate_dests.keys()):
        target_digit = fate_dests[pid]
        # Wrong room: pick a different fate destination
        wrong_digits = [d for d in [1, 4] if d != target_digit]
        if not wrong_digits:
            continue
        wrong_digit = wrong_digits[0]

        if target_digit not in room_centroids or wrong_digit not in room_centroids:
            continue

        # Full-dose perturbed cells (s=1.0)
        mask = (pert_ids_np == pid) & (pert_str == 1.0)
        if mask.sum() == 0:
            continue

        # Get source cells and predict trajectory
        src_label = pert_labels[mask][0]
        src_room_cells = data["homeostatic"][data["class_labels"] == src_label]
        rng = np.random.default_rng(123)
        n_pred = int(mask.sum())
        chosen = rng.integers(0, len(src_room_cells), size=n_pred)
        src_cells_batch = torch.from_numpy(src_room_cells[chosen]).float().to(DEVICE)
        pert_id_batch = torch.full((n_pred,), pid, dtype=torch.long, device=DEVICE)
        dose_batch = torch.ones(n_pred, device=DEVICE)

        z_src = encoder(src_cells_batch)
        z_pred = traj_pred(z_src, pert_id_batch, dose_batch)
        z_pred_mean = z_pred.mean(dim=0)

        # Also embed actual perturbed cells
        actual_pert = torch.from_numpy(pert_cells[mask]).float().to(DEVICE)
        z_actual = []
        for i in range(0, len(actual_pert), 256):
            z_actual.append(encoder(actual_pert[i:i+256]))
        z_actual = torch.cat(z_actual, dim=0)
        z_actual_mean = z_actual.mean(dim=0)

        # DR for predicted trajectories
        d_correct = (z_pred_mean - room_centroids[target_digit]).norm().item()
        d_wrong = (z_pred_mean - room_centroids[wrong_digit]).norm().item()
        dr_pred = d_wrong / (d_correct + 1e-8)

        # DR for actual perturbed cells (baseline)
        d_correct_a = (z_actual_mean - room_centroids[target_digit]).norm().item()
        d_wrong_a = (z_actual_mean - room_centroids[wrong_digit]).norm().item()
        dr_actual = d_wrong_a / (d_correct_a + 1e-8)

        pert_name = {0: "Fate-A→4", 1: "Fate-B→1", 2: "InRoom→4", 4: "Combo→4"}.get(pid, f"pert{pid}")
        status = "PASS" if dr_pred > 2.0 else ("PARTIAL" if dr_pred > 1.0 else "FAIL")
        print(f"  [{status}] {pert_name}: predicted DR={dr_pred:.2f}x  "
              f"(actual DR={dr_actual:.2f}x)")
        log_metrics(phase="B", event="trajectory", pert=pert_name,
                    predicted_DR=dr_pred, actual_DR=dr_actual)

        # Collect for UMAP
        umap_z.append(z_actual.cpu().numpy())
        umap_colors.extend([f"actual_p{pid}"] * len(z_actual))
        umap_z.append(z_pred.cpu().numpy())
        umap_colors.extend([f"pred_p{pid}"] * len(z_pred))

    # UMAP visualization
    Z_all = np.vstack(umap_z)
    reducer = umap.UMAP(metric="cosine", n_neighbors=15)
    emb_2d = reducer.fit_transform(Z_all)

    fig, ax = plt.subplots(1, 1, figsize=(10, 8))
    color_map = {
        "homeostatic": "#cccccc",
        "actual_p0": "#1f77b4", "pred_p0": "#aec7e8",
        "actual_p1": "#ff7f0e", "pred_p1": "#ffbb78",
        "actual_p2": "#2ca02c", "pred_p2": "#98df8a",
        "actual_p4": "#d62728", "pred_p4": "#ff9896",
    }
    for label in ["homeostatic", "actual_p0", "pred_p0", "actual_p1", "pred_p1",
                   "actual_p2", "pred_p2", "actual_p4", "pred_p4"]:
        mask = np.array([c == label for c in umap_colors])
        if mask.sum() == 0:
            continue
        alpha = 0.2 if label == "homeostatic" else 0.6
        size = 4 if label == "homeostatic" else 12
        marker = "o" if "actual" in label or label == "homeostatic" else "x"
        display = label.replace("actual_p", "actual pert ").replace("pred_p", "predicted pert ")
        ax.scatter(emb_2d[mask, 0], emb_2d[mask, 1],
                   c=color_map.get(label, "gray"), s=size, alpha=alpha,
                   marker=marker, label=display)

    ax.legend(loc="upper right", fontsize=8, markerscale=2)
    ax.set_title("Trajectory Prediction: Actual vs Predicted Perturbations")
    ax.set_xticks([])
    ax.set_yticks([])
    plt.tight_layout()
    fig.savefig(TRAIN_DIR / "phase_b_trajectories.png", dpi=150, bbox_inches="tight")
    plt.show()

    return


evaluate_trajectories(encoder_online, traj_predictor, data)

# %% [10] Final Summary
print("\n" + "=" * 60)
print(f"Phase A: {total_time:.1f}s  |  Phase B: {phase_b_time:.1f}s  |  "
      f"Total: {total_time + phase_b_time:.1f}s")
print("=" * 60)
evaluate_discrimination(encoder_online, data)
